steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - backend/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/backend:latest
      - --target
      - production
      - .
images:
  - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/backend:latest
options:
  logging: CLOUD_LOGGING_ONLY

