steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - frontend/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/frontend:latest
      - --target
      - production
      - --build-arg
      - VITE_API_BASE_URL=${_VITE_API_BASE_URL}
      - .
images:
  - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/frontend:latest
options:
  logging: CLOUD_LOGGING_ONLY

