"""VIZ-505 -- the chart-data acceptance matrix, shared with the Explorer.

The Explorer (``frontend/src/components/explore/exploreModel.ts``) offers only
the pickers whose requests ``parse_chart_spec`` accepts, so it mirrors the
server's refusal rules in ``apiRefusal``. A mirror drifts unless something holds
it to the original, and that is this file's fixture:
``contracts/viz/chart_data_combinations.json`` lists every ``group_by`` of one
or two dimensions (repeats included) x 0, 1 or 2 suite names x ``top_n`` of
none, 7 or 20, with the outcome the server gives: ``"ok"`` or the refusal
code. The frontend runs ``apiRefusal`` over the same cases.

The fixture lives beside ``flags.json``, not under ``contracts/viz/fixtures/``:
every JSON there is a ``<contract>/<valid|invalid>/`` fixture, and
``test_viz_contracts.py`` fails closed on anything else.

Regenerate it after a rule change with::

    python -m tests.test_chart_data_combinations

(from ``backend/``), then run the frontend ``exploreModel.test.ts``: a rule the
Explorer does not mirror fails there.
"""
from __future__ import annotations

import itertools
import json
import uuid
from pathlib import Path
from typing import Optional

import pytest

from app.core.analytics_errors import AnalyticsQueryError
from app.services import chart_data_service as svc
from app.services.analytics_scope import AnalyticsScope

FIXTURE = Path(__file__).resolve().parents[2] / "contracts" / "viz" / "chart_data_combinations.json"

#: The suite filters a case is asked under: none, exactly one, two.
SUITE_COUNTS = (0, 1, 2)
#: ``top_n`` values: absent, inside the series cap, past it (but a valid bucket count).
TOP_NS = (None, 7, 20)
SUITE_NAMES = ("checkout", "payments")


def _scope(suite_count: int) -> AnalyticsScope:
    """The scope ``test_chart_data._scope`` builds, with ``suite_count`` suites."""
    return AnalyticsScope(
        project_id=uuid.UUID("11111111-1111-1111-1111-111111111111"),
        allowed_project_ids=None,
        release_ids=(),
        suite_names=SUITE_NAMES[:suite_count],
        days=30,
    )  # type: ignore[arg-type]


def _group_bys() -> list[tuple[str, ...]]:
    """Every 1-tuple and every ordered 2-tuple (a repeat included) of the dimensions."""
    dims = list(svc.DIMENSIONS)
    return [(d,) for d in dims] + list(itertools.product(dims, repeat=2))


def outcome(metric: str, group_by: tuple[str, ...], suite_count: int, top_n: Optional[int]) -> str:
    """``"ok"``, or the refusal code ``parse_chart_spec`` raises."""
    try:
        svc.parse_chart_spec(metric, list(group_by), top_n, scope=_scope(suite_count))
    except AnalyticsQueryError as exc:
        return exc.code
    return "ok"


def build_fixture() -> dict:
    """The fixture as the server's rules give it today. The metric never decides
    acceptance (only that it is known), so cases are computed for one metric
    and the test below holds every other metric to them."""
    metric = next(iter(svc.METRICS))
    cases = [
        {
            "group_by": list(group_by),
            "suite_names": suite_count,
            "top_n": top_n,
            "outcome": outcome(metric, group_by, suite_count, top_n),
        }
        for group_by in _group_bys()
        for suite_count in SUITE_COUNTS
        for top_n in TOP_NS
    ]
    return {
        "description": (
            "VIZ-505: what GET /analytics/chart-data accepts, for every group_by of one or two "
            "dimensions x 0/1/2 suite names x top_n none/7/20. Generated by "
            "backend/tests/test_chart_data_combinations.py; mirrored by the Explorer's apiRefusal."
        ),
        "metrics": list(svc.METRICS),
        "dimensions": {
            name: {"time": dim.time, "high_cardinality": dim.high_cardinality}
            for name, dim in svc.DIMENSIONS.items()
        },
        "cases": cases,
    }


def render_fixture(fixture: dict) -> bytes:
    """One case per line, so a rule change is a readable diff. LF on every OS."""
    head = {key: value for key, value in fixture.items() if key != "cases"}
    lines = json.dumps(head, indent=2)[:-2]  # drop the closing "\n}"
    cases = ",\n".join(f"    {json.dumps(case, sort_keys=True)}" for case in fixture["cases"])
    return f'{lines},\n  "cases": [\n{cases}\n  ]\n}}\n'.encode("utf-8")


@pytest.fixture(scope="module")
def fixture() -> dict:
    assert FIXTURE.is_file(), f"{FIXTURE} is missing: run python -m tests.test_chart_data_combinations"
    return json.loads(FIXTURE.read_text(encoding="utf-8"))


def test_the_vocabularies_are_the_server_s(fixture: dict) -> None:
    assert fixture["metrics"] == list(svc.METRICS)
    assert fixture["dimensions"] == {
        name: {"time": dim.time, "high_cardinality": dim.high_cardinality}
        for name, dim in svc.DIMENSIONS.items()
    }


def test_the_cases_are_exactly_the_full_product(fixture: dict) -> None:
    """Fail closed: a dropped case would be a rule nobody checks."""
    seen = [
        (tuple(case["group_by"]), case["suite_names"], case["top_n"]) for case in fixture["cases"]
    ]
    expected = list(itertools.product(_group_bys(), SUITE_COUNTS, TOP_NS))
    assert len(seen) == len(set(seen)) == len(expected) == 132 * 9
    assert set(seen) == set(expected)


def test_every_metric_gives_the_fixture_s_outcome(fixture: dict) -> None:
    wrong = [
        (metric, case)
        for metric in svc.METRICS
        for case in fixture["cases"]
        if outcome(metric, tuple(case["group_by"]), case["suite_names"], case["top_n"])
        != case["outcome"]
    ]
    assert wrong == [], f"{len(wrong)} cases disagree; regenerate the fixture: {wrong[:5]}"


def test_the_fixture_is_byte_identical_to_a_regeneration() -> None:
    """The file on disk is what ``__main__`` writes, so a hand edit cannot hide."""
    assert FIXTURE.read_bytes() == render_fixture(build_fixture())


def test_the_matrix_exercises_every_refusal_the_explorer_mirrors(fixture: dict) -> None:
    """A fixture where every case is ok would hold the mirror to nothing."""
    codes = {case["outcome"] for case in fixture["cases"]}
    assert codes == {
        "ok",
        "unique_dimension",
        "high_cardinality_pair",
        "time_dimension_position",
        "top_n_range",
        "top_n_unsupported",
        "test_requires_scope",
    }


if __name__ == "__main__":  # pragma: no cover - the regenerator
    FIXTURE.write_bytes(render_fixture(build_fixture()))
    print(f"wrote {FIXTURE}")
