"""Weekly flaky-debt review draft (Agentic plan AI-7).

Builds a per-team, TEXT-ONLY review of the project's flaky-test debt on the
weekly digest cadence:

* **quarantined** — the team's currently-active quarantine entries (owner
  from the US-5.4 lifecycle fields);
* **stale** — active entries past their SLA (``stale_at`` <= now);
* **ready to promote** — entries whose pass streak crossed the promotion
  threshold (US-5.5);
* **newly flaky** — entries detected inside the review window;

with one deterministic suggested next step per entry (promote / review the
SLA breach / investigate the new flake / re-check the rationale).

Delivery (US-7.3 routing, weekly cadence):

* Teams WITH an active ``team_notification_channels`` row get their draft on
  their own channel via the Monday beat task
  (``dispatch_weekly_flaky_debt_reviews`` → :func:`deliver_flaky_debt_reviews`).
* Teams WITHOUT a channel fold into the project's weekly digest as a
  "Weekly flaky-debt review" section (``digest_content_service`` reads
  :func:`build_flaky_debt_reviews` and excludes channel-routed teams).
  This fold-in is unconditional-when-data-exists: an opt-in subscription
  flag would need a schema change (the ``send_when_unchanged`` /
  ``report_attachment`` precedents were migrations 0106/0107) and this
  slice ships without migrations.

Trust doctrine: every rendered draft opens with :data:`REVIEW_LABEL`; all
content is deterministic — **this module never calls an LLM** (guarded by
``tests/test_proactive_narratives.py``) and every number comes from the
quarantine lifecycle rows the dashboard already shows. Teams with no debt
produce no draft at all.
"""
from __future__ import annotations

import uuid
from datetime import datetime, timedelta, timezone
from typing import Any, Optional

import structlog
from sqlalchemy import or_, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import settings
from app.models.postgres import (
    FlakyQuarantineRequest,
    FlakyQuarantineStatus,
    Project,
    TeamNotificationChannel,
    User,
)

logger = structlog.get_logger("services.flaky_debt_review")

# The automation label every draft opens with (trust doctrine: all AI /
# automation text is clearly labeled). Keep the wording stable — tests pin it.
REVIEW_LABEL = (
    "Automated draft — generated by TestLookup's flaky-debt automation "
    "(informational; verify before acting)."
)

# Active-enforcement statuses (same triple the digest delta uses).
_ACTIVE_QUARANTINE_STATUSES = (
    FlakyQuarantineStatus.QUARANTINED.value,
    FlakyQuarantineStatus.RECHECK_SCHEDULED.value,
    FlakyQuarantineStatus.RE_QUARANTINED.value,
)

# Fallback bucket for tests no ownership rule claims.
UNASSIGNED_TEAM = "Unassigned"

# Per-bucket row cap in the rendered text (keeps channel messages bounded).
BUCKET_ROW_CAP = 10

# Presentation order + headings for the four buckets.
_BUCKET_ORDER: tuple[tuple[str, str], ...] = (
    ("ready_to_promote", "Ready to promote"),
    ("stale", "Stale over SLA"),
    ("newly_flaky", "Newly flaky this window"),
    ("quarantined", "Quarantined (active)"),
)


# ── Pure helpers (unit-tested directly) ──────────────────────────────────────


def suggest_next_step(entry: dict[str, Any], base_url: str) -> str:
    """Deterministic suggested next step for one debt entry.

    Priority: promote > review SLA breach > investigate new flake >
    re-check rationale.
    """
    if entry.get("ready_to_promote"):
        passes = int(entry.get("consecutive_passes") or 0)
        streak = f" ({passes} consecutive passing runs)" if passes else ""
        return (
            f"Promote — stability streak reached{streak}; "
            f"release from quarantine: {base_url}/quarantine"
        )
    if entry.get("stale"):
        since = str(entry.get("stale_at") or "")[:10]
        since_str = f" (stale since {since})" if since else ""
        return (
            f"Review — quarantine exceeded its SLA{since_str}; "
            f"fix the test or extend with a reason: {base_url}/quarantine"
        )
    if entry.get("newly_flaky"):
        return (
            f"Investigate — newly flaky this window; triage it in the "
            f"Flaky Coach: {base_url}/flaky-coach"
        )
    return (
        f"Review reason — confirm the quarantine rationale still holds: "
        f"{base_url}/quarantine"
    )


def group_entries_by_team(entries: list[dict[str, Any]]) -> dict[str, dict[str, list]]:
    """Group entries into per-team buckets. An entry can appear in several
    buckets (e.g. active AND stale). Teams with zero entries never appear."""
    teams: dict[str, dict[str, list]] = {}
    for entry in entries:
        team = entry.get("team") or UNASSIGNED_TEAM
        buckets = teams.setdefault(
            team,
            {"quarantined": [], "stale": [], "ready_to_promote": [], "newly_flaky": []},
        )
        if entry.get("active"):
            buckets["quarantined"].append(entry)
        if entry.get("stale"):
            buckets["stale"].append(entry)
        if entry.get("ready_to_promote"):
            buckets["ready_to_promote"].append(entry)
        if entry.get("newly_flaky"):
            buckets["newly_flaky"].append(entry)
    return teams


def _entry_line(entry: dict[str, Any]) -> str:
    suite = entry.get("suite_name")
    suite_str = f" ({suite})" if suite else ""
    owner = entry.get("owner")
    owner_str = f" — owner: {owner}" if owner else " — owner: unassigned"
    return (
        f"  - {entry.get('test_name') or entry.get('test_fingerprint') or 'unknown test'}"
        f"{suite_str}{owner_str}\n"
        f"    next: {entry.get('next_step') or ''}"
    )


def render_team_review_text(
    team: str,
    buckets: dict[str, list],
    *,
    window_start: str,
    window_end: str,
    base_url: str,
) -> Optional[str]:
    """One team's draft as plain text (TEXT ONLY — the trust doctrine for
    this surface). Returns ``None`` when every bucket is empty."""
    if not any(buckets.get(key) for key, _ in _BUCKET_ORDER):
        return None
    lines = [
        f"Weekly flaky-debt review — {team}",
        f"Window: {window_start[:10]} → {window_end[:10]}",
        REVIEW_LABEL,
    ]
    for key, heading in _BUCKET_ORDER:
        bucket = buckets.get(key) or []
        if not bucket:
            continue
        lines.append("")
        lines.append(f"{heading} ({len(bucket)}):")
        for entry in bucket[:BUCKET_ROW_CAP]:
            lines.append(_entry_line(entry))
        overflow = len(bucket) - BUCKET_ROW_CAP
        if overflow > 0:
            lines.append(f"  … +{overflow} more — see {base_url}/quarantine")
    lines.append("")
    lines.append(
        f"Full quarantine board: {base_url}/quarantine · "
        f"Flaky Coach: {base_url}/flaky-coach"
    )
    return "\n".join(lines)


# ── Collection ───────────────────────────────────────────────────────────────


async def collect_flaky_debt_entries(
    db: AsyncSession,
    project_id: uuid.UUID,
    since: datetime,
    now: datetime,
) -> list[dict[str, Any]]:
    """All debt-relevant quarantine rows for the project, each resolved to a
    team via the US-7.3 ownership rules (fallback :data:`UNASSIGNED_TEAM`)
    and annotated with lifecycle flags + a suggested next step.

    Rows considered: currently-active quarantines (standing debt) plus any
    row detected inside the window (newly flaky, whatever its status).
    """
    from app.services.ownership_resolver_service import (
        load_rules_for_project,
        resolve_test_ownership,
    )

    rows = (
        (
            await db.execute(
                select(FlakyQuarantineRequest)
                .where(
                    FlakyQuarantineRequest.project_id == project_id,
                    or_(
                        FlakyQuarantineRequest.status.in_(_ACTIVE_QUARANTINE_STATUSES),
                        FlakyQuarantineRequest.detected_at >= since,
                    ),
                )
                .order_by(FlakyQuarantineRequest.detected_at.desc())
            )
        )
        .scalars()
        .all()
    )
    if not rows:
        return []

    # Owner display names — one batched lookup (US-5.4 lifecycle owner).
    owner_ids = {r.owner_user_id for r in rows if r.owner_user_id}
    owners: dict[uuid.UUID, str] = {}
    if owner_ids:
        user_rows = (
            await db.execute(
                select(User.id, User.full_name, User.email).where(User.id.in_(owner_ids))
            )
        ).all()
        owners = {u.id: (u.full_name or u.email) for u in user_rows}

    # Team resolution — same rules + component map the report/routing use.
    rules = await load_rules_for_project(db, project_id)
    project = (
        await db.execute(select(Project).where(Project.id == project_id))
    ).scalar_one_or_none()
    component_owner_map = project.component_owner_map if project else None

    base_url = settings.public_base_url
    entries: list[dict[str, Any]] = []
    for row in rows:
        team: Optional[str] = None
        try:
            resolution = resolve_test_ownership(
                rules,
                {
                    "suite_name": row.suite_name or "",
                    "component": "",
                    "package": "",
                    "path": row.test_name or "",
                    "label": "",
                    "owner": "",
                },
                component_owner_map,
            )
            team = resolution.team_name or None
        except Exception as exc:  # noqa: BLE001 — one bad rule must not kill the review
            logger.warning(
                "flaky_debt_team_resolution_failed",
                project_id=str(project_id),
                test_name=row.test_name,
                error=str(exc),
            )
        detected_at = row.detected_at
        if detected_at is not None and detected_at.tzinfo is None:
            detected_at = detected_at.replace(tzinfo=timezone.utc)
        entry: dict[str, Any] = {
            "test_name": row.test_name,
            "test_fingerprint": row.test_fingerprint,
            "suite_name": row.suite_name,
            "status": row.status,
            "team": team or UNASSIGNED_TEAM,
            "owner": owners.get(row.owner_user_id),
            "active": row.status in _ACTIVE_QUARANTINE_STATUSES,
            "stale": bool(row.stale),
            "ready_to_promote": bool(row.ready_to_promote),
            "newly_flaky": bool(detected_at is not None and since <= detected_at < now),
            "consecutive_passes": int(row.consecutive_passes or 0),
            "stale_at": row.stale_at.isoformat() if row.stale_at else None,
            "detected_at": detected_at.isoformat() if detected_at else None,
            "flip_rate": float(row.flip_rate) if row.flip_rate is not None else None,
        }
        entry["next_step"] = suggest_next_step(entry, base_url)
        entries.append(entry)
    return entries


async def build_flaky_debt_reviews(
    db: AsyncSession,
    project_id: uuid.UUID,
    since: datetime | None = None,
    now: datetime | None = None,
) -> dict[str, Any]:
    """The full per-team review set for one project.

    Returns ``{"window_start", "window_end", "teams": [{"team", "counts",
    "text"}, …]}`` — teams sorted by total debt descending; teams with no
    entries are omitted entirely.
    """
    now = now or datetime.now(timezone.utc)
    since = since or (now - timedelta(days=7))
    entries = await collect_flaky_debt_entries(db, project_id, since, now)
    grouped = group_entries_by_team(entries)

    window_start = since.isoformat()
    window_end = now.isoformat()
    base_url = settings.public_base_url

    teams: list[dict[str, Any]] = []
    for team, buckets in grouped.items():
        text = render_team_review_text(
            team, buckets,
            window_start=window_start, window_end=window_end, base_url=base_url,
        )
        if text is None:
            continue
        teams.append({
            "team": team,
            "counts": {key: len(buckets.get(key) or []) for key, _ in _BUCKET_ORDER},
            "text": text,
        })
    teams.sort(key=lambda t: -sum(t["counts"].values()))
    return {"window_start": window_start, "window_end": window_end, "teams": teams}


# ── Weekly delivery through US-7.3 team channels ─────────────────────────────


async def deliver_flaky_debt_reviews(now: datetime | None = None) -> dict[str, int]:
    """Weekly beat body: for every project with active team channels, send
    each channel-mapped team its draft. Teams without channels are NOT sent
    from here — their drafts fold into the project's weekly digest instead
    (``digest_content_service``).

    Owns its sessions (Celery-task path). Never raises past a project —
    one broken project must not starve the rest. Returns counters for the
    task log: ``{"projects": N, "sent": N, "failed": N}``.
    """
    from app.db.postgres import AsyncSessionLocal
    from app.services.notification_routing import (
        load_team_channels,
        record_team_delivery_logs,
        send_to_team_channel,
    )

    now = now or datetime.now(timezone.utc)
    counters = {"projects": 0, "sent": 0, "failed": 0}

    async with AsyncSessionLocal() as db:
        project_ids = [
            row[0]
            for row in (
                await db.execute(
                    select(TeamNotificationChannel.project_id)
                    .where(TeamNotificationChannel.is_active == True)  # noqa: E712
                    .distinct()
                )
            ).all()
        ]

    for project_id in project_ids:
        try:
            async with AsyncSessionLocal() as db:
                channels = await load_team_channels(db, project_id)
                if not channels:
                    continue
                reviews = await build_flaky_debt_reviews(db, project_id, now=now)
                project_name = (
                    await db.execute(select(Project.name).where(Project.id == project_id))
                ).scalar_one_or_none() or str(project_id)

            counters["projects"] += 1
            log_entries = []
            for team_review in reviews["teams"]:
                channel = channels.get(team_review["team"])
                if channel is None:
                    continue  # folds into the weekly digest instead
                title = (
                    f"TestLookup — Weekly flaky-debt review — "
                    f"{project_name} / {team_review['team']}"
                )
                status, error_detail = await send_to_team_channel(
                    channel,
                    title,
                    team_review["text"],
                    "flaky_debt_review",
                    {"project_id": str(project_id), "team": team_review["team"]},
                )
                counters["sent" if status == "sent" else "failed"] += 1
                log_entries.append(
                    (channel, "flaky_debt_review", title, team_review["text"],
                     status, error_detail)
                )
            await record_team_delivery_logs(project_id, None, log_entries)
        except Exception as exc:  # noqa: BLE001 — per-project fail-open
            logger.warning(
                "flaky_debt_review_project_failed",
                project_id=str(project_id),
                error=str(exc),
            )
    logger.info("flaky_debt_reviews_dispatched", **counters)
    return counters
