"""Async MongoDB client using Motor."""
from typing import Optional

from motor.motor_asyncio import AsyncIOMotorClient, AsyncIOMotorDatabase

from app.core.config import settings

_client: Optional[AsyncIOMotorClient] = None


def get_mongo_client() -> AsyncIOMotorClient:
    global _client
    if _client is None:
        _client = AsyncIOMotorClient(
            settings.MONGO_URI,
            serverSelectionTimeoutMS=5000,
            connectTimeoutMS=10000,
            maxPoolSize=settings.MONGO_MAX_POOL_SIZE,
            minPoolSize=settings.MONGO_MIN_POOL_SIZE,
            socketTimeoutMS=settings.MONGO_SOCKET_TIMEOUT_MS,
            maxIdleTimeMS=settings.MONGO_MAX_IDLE_TIME_MS,
        )
    return _client


def get_mongo_db() -> AsyncIOMotorDatabase:
    return get_mongo_client()[settings.MONGO_DB]


async def close_mongo() -> None:
    global _client
    if _client is not None:
        _client.close()  # Motor's close() is synchronous (returns None, not a coroutine)
        _client = None


# Collection name constants
class Collections:
    RAW_ALLURE_JSON = "raw_allure_json"
    RAW_TESTNG_XML = "raw_testng_xml"
    REST_API_PAYLOADS = "rest_api_payloads"
    EXECUTION_LOGS = "execution_logs"
    AI_ANALYSIS_PAYLOADS = "ai_analysis_payloads"
    OCP_POD_EVENTS = "ocp_pod_events"
    RUN_SUMMARIES = "run_summaries"           # Generated by SummaryAgent
    LIVE_EXECUTION_EVENTS = "live_execution_events"  # Raw events from live runner
