"""Async MongoDB client using Motor."""
from typing import Optional

from motor.motor_asyncio import AsyncIOMotorClient, AsyncIOMotorDatabase

from app.core.config import settings

_client: Optional[AsyncIOMotorClient] = None


def get_mongo_client() -> AsyncIOMotorClient:
    global _client
    if _client is None:
        _client = AsyncIOMotorClient(
            settings.MONGO_URI,
            serverSelectionTimeoutMS=5000,
            connectTimeoutMS=10000,
            maxPoolSize=settings.MONGO_MAX_POOL_SIZE,
            minPoolSize=settings.MONGO_MIN_POOL_SIZE,
            socketTimeoutMS=settings.MONGO_SOCKET_TIMEOUT_MS,
            maxIdleTimeMS=settings.MONGO_MAX_IDLE_TIME_MS,
        )
    return _client


def get_mongo_db() -> AsyncIOMotorDatabase:
    return get_mongo_client()[settings.MONGO_DB]


async def close_mongo() -> None:
    global _client
    if _client is not None:
        _client.close()  # Motor's close() is synchronous (returns None, not a coroutine)
        _client = None


async def ensure_indexes() -> None:
    """
    Create indexes on hot-path Mongo collections.

    Idempotent — safe to call on every startup. Runs in the background so a
    transient Mongo hiccup cannot block the API lifespan. Must be kept in sync
    with the query patterns in ``app/tools/`` and ``app/services/ingestion.py``
    — any new lookup field needs a matching index here.
    """
    db = get_mongo_db()
    specs = [
        # Hot path: tools/fetch_rest_payload.py — lookup by test_case_id.
        (Collections.REST_API_PAYLOADS, [("test_case_id", 1)], {}),
        # Hot path: tools/fetch_stacktrace.py
        (Collections.RAW_ALLURE_JSON, [("test_case_id", 1)], {}),
        (Collections.RAW_TESTNG_XML, [("test_case_id", 1)], {}),
        # Splunk log correlation window — by run + timestamp.
        (Collections.EXECUTION_LOGS, [("test_run_id", 1), ("timestamp", -1)], {}),
        # AI analysis audit — lookup per test case.
        (Collections.AI_ANALYSIS_PAYLOADS, [("test_case_id", 1)], {}),
        # OCP pod events correlation — by run + timestamp.
        (Collections.OCP_POD_EVENTS, [("test_run_id", 1), ("timestamp", -1)], {}),
        # Run summaries keyed by run_id.
        (Collections.RUN_SUMMARIES, [("test_run_id", 1)], {"unique": True}),
        # Live event timeline — session_id + seq.
        (Collections.LIVE_EXECUTION_EVENTS, [("session_id", 1), ("seq", 1)], {}),
        # Retention purge (US-11.4): the webhook ingest path writes these
        # docs keyed by run_id (routers/live.py), and the purge deletes by
        # run_id — without this index every purge collection-scans.
        (Collections.LIVE_EXECUTION_EVENTS, [("run_id", 1)], {}),
    ]
    for coll, keys, kwargs in specs:
        try:
            await db[coll].create_index(keys, background=True, **kwargs)
        except Exception as exc:  # pragma: no cover — non-fatal
            # Never let index creation block startup; the query path still works.
            import logging
            logging.getLogger("db.mongo").warning(
                "Failed to create index on %s %s: %s", coll, keys, exc,
            )


# Collection name constants
class Collections:
    RAW_ALLURE_JSON = "raw_allure_json"
    RAW_TESTNG_XML = "raw_testng_xml"
    REST_API_PAYLOADS = "rest_api_payloads"
    EXECUTION_LOGS = "execution_logs"
    AI_ANALYSIS_PAYLOADS = "ai_analysis_payloads"
    OCP_POD_EVENTS = "ocp_pod_events"
    RUN_SUMMARIES = "run_summaries"           # Generated by SummaryAgent
    LIVE_EXECUTION_EVENTS = "live_execution_events"  # Raw events from live runner
