import { test, expect } from '@playwright/test'
const BASE = 'http://testlookup.local'
test('run detail renders the uploaded run faithfully', async ({ page }) => {
  await page.goto(`${BASE}/login`)
  await page.fill('input[name="username"], input[type="text"]', 'admin')
  await page.fill('input[type="password"]', 'Admin@2026!')
  await page.click('button[type="submit"]')
  await page.waitForTimeout(7000)
  const sel = page.locator('select').first()
  const opts = await sel.locator('option').allTextContents()
  await sel.selectOption({ label: opts.find(o => /uat onboarding/i.test(o))! })
  await page.waitForTimeout(2500)
  await page.goto(`${BASE}/runs`)
  await page.waitForTimeout(6000)
  const link = page.locator('a[href*="/runs/"]').first()
  console.log('run links:', await page.locator('a[href*="/runs/"]').count())
  await link.click()
  await page.waitForTimeout(8000)
  const body = await page.locator('body').innerText()
  console.log('=== RUN DETAIL ===')
  console.log(body.slice(0, 2600))
  const low = body.toLowerCase()
  console.log('\n--- assertions ---')
  console.log('shows a 6 total:', /\b6\b/.test(body))
  console.log('unicode test name present:', body.includes('🛒'))
  console.log('broken/error test present:', low.includes('test_db_reachable'))
  console.log('40% pass rate shown:', /40(\.0)?\s*%/.test(body))
  expect(true).toBe(true)
})
