#!/usr/bin/env bash
# gen-dev-env.sh — generate a ready-to-run .env for LOCAL / DEMO use.
#
# Removes the #1 first-run friction: instead of hand-editing .env.example and
# running `openssl rand` eight times, this fills every required secret with a
# freshly generated random value and keeps the connection strings
# (DATABASE_URL / MONGO_URI) in sync with the passwords it generated, so
# `docker compose up` works on the first try.
#
# The generated .env is for LOCAL DEVELOPMENT / DEMO ONLY — it is git-ignored
# and clearly marked not-for-production.
#
# Usage:
#   scripts/gen-dev-env.sh            # no-op if .env already exists
#   scripts/gen-dev-env.sh --force    # overwrite an existing .env
set -euo pipefail

cd "$(dirname "$0")/.."

ENV_FILE=".env"
EXAMPLE=".env.example"
FORCE=0
[ "${1:-}" = "--force" ] && FORCE=1

if [ ! -f "$EXAMPLE" ]; then
  echo "error: $EXAMPLE not found (run from the repo root)" >&2
  exit 1
fi

if [ -f "$ENV_FILE" ] && [ "$FORCE" -ne 1 ]; then
  echo "$ENV_FILE already exists — leaving it untouched (use --force to regenerate)."
  exit 0
fi

# ── secret generator: openssl → python → /dev/urandom, in that order ──────────
rand() { # rand <hex|b64|alnum> <bytes>
  local kind="$1" n="$2"
  if command -v openssl >/dev/null 2>&1; then
    case "$kind" in
      hex) openssl rand -hex "$n" | tr -d '\r\n' ;;
      b64) openssl rand -base64 "$n" | tr -d '\r\n=/+' ;;
      alnum) openssl rand -hex "$n" | tr -d '\r\n' ;;
    esac
  elif command -v python3 >/dev/null 2>&1; then
    python3 -c "import secrets,sys; k=sys.argv[1]; n=int(sys.argv[2]); print(secrets.token_hex(n) if k!='b64' else secrets.token_urlsafe(n).replace('-','').replace('_',''))" "$kind" "$n"
  else
    head -c "$n" /dev/urandom | od -An -tx1 | tr -d ' \n'
  fi
}

POSTGRES_PW="$(rand hex 24)"
MONGO_PW="$(rand hex 24)"
REDIS_PW="$(rand hex 24)"
MINIO_AK="tl$(rand alnum 6)"
MINIO_SK="$(rand b64 32)"
FLOWER_PW="$(rand hex 16)"
APP_SECRET="$(rand hex 32)"
JWT_SECRET="$(rand hex 32)"
WEBHOOK_SECRET="$(rand hex 32)"
GF_ADMIN_PW="$(rand hex 16)"

PG_USER="testlookup_user"; PG_DB="testlookup"
MONGO_USER="testlookup"; MONGO_DB="testlookup_logs"

# Start from the documented example, then overwrite the secret-bearing lines so
# all the explanatory comments + non-secret defaults are preserved.
cp "$EXAMPLE" "$ENV_FILE"

# set_kv KEY VALUE — replace `KEY=...` in place (portable: rewrite via python).
set_kv() {
  ENV_FILE="$ENV_FILE" python3 - "$1" "$2" <<'PY'
import os, re, sys
key, val = sys.argv[1], sys.argv[2]
p = os.environ["ENV_FILE"]
lines = open(p, encoding="utf-8").read().splitlines()
pat = re.compile(rf"^{re.escape(key)}=")
out, found = [], False
for ln in lines:
    if pat.match(ln) and not found:
        out.append(f"{key}={val}"); found = True
    else:
        out.append(ln)
if not found:
    out.append(f"{key}={val}")
open(p, "w", encoding="utf-8", newline="\n").write("\n".join(out) + "\n")
PY
}

set_kv POSTGRES_PASSWORD "$POSTGRES_PW"
set_kv DATABASE_URL "postgresql+asyncpg://${PG_USER}:${POSTGRES_PW}@localhost:5433/${PG_DB}"
set_kv MONGO_PASSWORD "$MONGO_PW"
set_kv MONGO_URI "mongodb://${MONGO_USER}:${MONGO_PW}@localhost:27017/${MONGO_DB}?authSource=admin"
set_kv REDIS_PASSWORD "$REDIS_PW"
set_kv REDIS_URL "redis://:${REDIS_PW}@localhost:6379/0"
set_kv CELERY_BROKER_URL "redis://:${REDIS_PW}@localhost:6379/0"
set_kv CELERY_RESULT_BACKEND "redis://:${REDIS_PW}@localhost:6379/1"
set_kv MINIO_ACCESS_KEY "$MINIO_AK"
set_kv MINIO_SECRET_KEY "$MINIO_SK"
set_kv FLOWER_PASSWORD "$FLOWER_PW"
set_kv APP_SECRET_KEY "$APP_SECRET"
set_kv JWT_SECRET_KEY "$JWT_SECRET"
set_kv WEBHOOK_SECRET "$WEBHOOK_SECRET"
set_kv GF_SECURITY_ADMIN_PASSWORD "$GF_ADMIN_PW"
# Local convenience: gen-dev-env is the LOCAL/DEMO path, so restore the dev
# affordances the secure .env.example defaults turn off (passwordless dev-login
# on APP_ENV=development). Real deployments use the .env.example defaults.
set_kv APP_ENV "development"
set_kv APP_DEBUG "true"
set_kv DEV_AUTO_LOGIN_ENABLED "true"

# Stamp a clear local-only banner at the top.
python3 - "$ENV_FILE" <<'PY'
import sys
p = sys.argv[1]
banner = (
    "# -------------------------------------------------------------\n"
    "# AUTO-GENERATED by scripts/gen-dev-env.sh for LOCAL / DEMO use.\n"
    "# Secrets below are random and safe for a local machine ONLY.\n"
    "# DO NOT use this file in production -- generate fresh secrets there.\n"
    "# -------------------------------------------------------------\n"
)
# Read the existing content FIRST, then truncate+write — opening in "w" mode
# truncates immediately, so reading must happen before the open-for-write.
existing = open(p, encoding="utf-8").read()
open(p, "w", encoding="utf-8", newline="\n").write(banner + existing)
PY

echo "Wrote $ENV_FILE with generated local secrets (DATABASE_URL / MONGO_URI kept in sync)."
