#!/usr/bin/env python3
"""mypy as a ratchet: the per-file error count may only go down (re-audit M24).

``mypy app/`` reported 391 errors in 117 files on 2026-09-11 (mypy 2.3.1, the
version pinned in ``backend/requirements.txt``). Fixing all of them in one change
is not a reviewable diff, and ``continue-on-error: true`` meant a NEW type error
was invisible. This script makes mypy blocking without a flag day:

* ``backend/mypy-baseline.txt`` lists ``<count> <path>`` per file that has errors
  today;
* a file whose count goes UP, or a file not in the baseline that gains an error,
  fails the build;
* a file whose count went DOWN passes and prints a hint to tighten the
  baseline (``--update``), which can only lower counts unless
  ``--allow-increase`` is given explicitly.

Fails closed: if mypy crashed (exit code 2) or printed no summary line, the run
is an error, never "0 errors".

Usage (from ``backend/``)::

    python ../scripts/mypy_ratchet.py            # run mypy, compare
    python ../scripts/mypy_ratchet.py --update   # lower the baseline after fixes
    python ../scripts/mypy_ratchet.py --from-log mypy.log   # compare a saved run
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from collections import Counter
from pathlib import Path

BACKEND = Path(__file__).resolve().parent.parent / "backend"
BASELINE = BACKEND / "mypy-baseline.txt"
# ``--platform linux``: CI runs on ubuntu, and ``sys.platform`` branches change
# what mypy checks. Pinning it makes a Windows or macOS run count exactly what
# CI counts, so the baseline means the same number everywhere.
MYPY_ARGS = ["app/", "--ignore-missing-imports", "--platform", "linux"]

# ``app/x.py:12: error: ...`` / ``app\x.py:12:5: error: ...`` (Windows, columns)
_ERROR_LINE = re.compile(r"^(?P<path>[^:\s][^:]*?\.pyi?):\d+(?::\d+)?: error: ")
_SUMMARY = re.compile(r"^(Found \d+ errors? in \d+ files?|Success: no issues found)")


class RatchetError(Exception):
    """mypy output could not be trusted — never read as a pass."""


def parse_mypy_output(text: str, exit_code: int | None = None) -> Counter[str]:
    """Per-file error counts from mypy's default output format."""
    if exit_code is not None and exit_code not in (0, 1):
        raise RatchetError(f"mypy exited {exit_code} (crash or usage error)")
    lines = text.splitlines()
    if not any(_SUMMARY.match(line) for line in lines):
        raise RatchetError("mypy printed no summary line; refusing to treat it as clean")
    counts: Counter[str] = Counter()
    for line in lines:
        match = _ERROR_LINE.match(line)
        if match:
            counts[match.group("path").replace("\\", "/")] += 1
    return counts


def load_baseline(path: Path = BASELINE) -> dict[str, int]:
    baseline: dict[str, int] = {}
    if not path.exists():
        return baseline
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        count, file = line.split(maxsplit=1)
        baseline[file] = int(count)
    return baseline


def compare(current: Counter[str], baseline: dict[str, int]) -> tuple[list[str], list[str]]:
    """``(regressions, improvements)`` as human-readable lines."""
    regressions: list[str] = []
    improvements: list[str] = []
    for file in sorted(set(current) | set(baseline)):
        now, allowed = current.get(file, 0), baseline.get(file, 0)
        if now > allowed:
            regressions.append(f"{file}: {now} errors (baseline {allowed})")
        elif now < allowed:
            improvements.append(f"{file}: {now} errors (baseline {allowed})")
    return regressions, improvements


def render_baseline(counts: dict[str, int]) -> str:
    header = (
        "# mypy error ratchet (re-audit M24). Generated by scripts/mypy_ratchet.py --update.\n"
        "# <count> <path>. Counts may only go DOWN; see the script docstring.\n"
    )
    body = "".join(f"{counts[f]} {f}\n" for f in sorted(counts) if counts[f] > 0)
    return header + body


def update_baseline(current: Counter[str], baseline: dict[str, int], allow_increase: bool,
                    path: Path = BASELINE) -> list[str]:
    """Write the new baseline. Returns the lines that would have raised a count
    (and refuses to write when there are any, unless ``allow_increase``)."""
    raised = [
        f"{f}: {current[f]} > {baseline.get(f, 0)}"
        for f in sorted(current)
        if current[f] > baseline.get(f, 0)
    ]
    if raised and not allow_increase and baseline:
        return raised
    path.write_bytes(render_baseline(dict(current)).encode("utf-8"))
    return []


def run_mypy() -> tuple[str, int]:
    proc = subprocess.run(
        [sys.executable, "-m", "mypy", *MYPY_ARGS],
        cwd=BACKEND, capture_output=True, text=True, encoding="utf-8", errors="replace",
    )
    return proc.stdout + proc.stderr, proc.returncode


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--from-log", type=Path, help="compare a saved mypy output instead of running mypy")
    parser.add_argument("--update", action="store_true", help="rewrite the baseline from this run")
    parser.add_argument("--allow-increase", action="store_true", help="let --update raise a count")
    parser.add_argument("--baseline", type=Path, default=BASELINE)
    args = parser.parse_args(argv)

    if args.from_log:
        text, code = args.from_log.read_text(encoding="utf-8", errors="replace"), None
    else:
        text, code = run_mypy()
    try:
        current = parse_mypy_output(text, code)
    except RatchetError as exc:
        print(text[-4000:])
        print(f"::error::mypy ratchet: {exc}")
        return 2

    baseline = load_baseline(args.baseline)
    total, allowed = sum(current.values()), sum(baseline.values())

    if args.update:
        raised = update_baseline(current, baseline, args.allow_increase, args.baseline)
        if raised:
            print("refusing to RAISE baseline counts without --allow-increase:")
            print("\n".join(f"  {line}" for line in raised))
            return 1
        print(f"baseline written: {total} errors in {len(current)} files")
        return 0

    regressions, improvements = compare(current, baseline)
    print(f"mypy: {total} errors in {len(current)} files (baseline {allowed})")
    if improvements:
        print("fewer errors than the baseline allows; tighten it with "
              "`python ../scripts/mypy_ratchet.py --update`:")
        print("\n".join(f"  {line}" for line in improvements))
    if regressions:
        # Show the offending errors themselves, not only the counts.
        bad = {line.split(":", 1)[0] for line in regressions}
        for line in text.splitlines():
            match = _ERROR_LINE.match(line)
            if match and match.group("path").replace("\\", "/") in bad:
                print(line)
        print("::error::new mypy errors (count went up):")
        print("\n".join(f"  {line}" for line in regressions))
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
