#!/usr/bin/env python3
"""TestLookup quality gates — single entry point.

Each guard codifies one cross-cutting invariant from CLAUDE.md so future
changes cannot silently degrade code quality. Run locally with::

    make quality-gate

or directly::

    python scripts/quality_gate.py             # run every guard
    python scripts/quality_gate.py --list      # show guard names
    python scripts/quality_gate.py --only backend.no-print frontend.clipboard-util

Guards are grouped by surface (``backend``, ``frontend``, ``database``,
``agents``). Each guard:

* Walks the relevant files.
* Reports violations as ``file:line: message``.
* Subtracts the baseline at ``scripts/quality-gate-baselines/<name>.txt``
  (one ``file:line`` per line, ``#`` comments allowed) so existing,
  intentional exceptions stay tolerated. **New** violations fail the
  guard (exit code 1). This is the "ratchet" the team agreed on — gates
  only get stricter from here.

To accept a new baseline entry (rare — usually you fix the code instead):

    python scripts/quality_gate.py --only <guard> --update-baseline

The CI workflow runs this script as a required job. ``--update-baseline``
is *not* run in CI, so a baseline change must be reviewed in a PR.
"""
from __future__ import annotations

import argparse
import ast
import hashlib
import io
import json
import re
import sys
import tokenize
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable, Iterable, Optional

REPO_ROOT = Path(__file__).resolve().parent.parent
BASELINE_DIR = REPO_ROOT / "scripts" / "quality-gate-baselines"

# Colour helpers — disabled when the terminal isn't a TTY (CI logs).
_USE_COLOR = sys.stdout.isatty() if hasattr(sys.stdout, "isatty") else False
RED = "\033[31m" if _USE_COLOR else ""
GREEN = "\033[32m" if _USE_COLOR else ""
YELLOW = "\033[33m" if _USE_COLOR else ""
BLUE = "\033[34m" if _USE_COLOR else ""
DIM = "\033[2m" if _USE_COLOR else ""
RESET = "\033[0m" if _USE_COLOR else ""


@dataclass
class Violation:
    """One occurrence of a forbidden pattern. ``key`` is what we match
    against the baseline file (``file:line``) so the baseline survives
    surrounding whitespace/comment changes."""

    file: Path
    line: int
    message: str

    @property
    def key(self) -> str:
        return f"{self.file.relative_to(REPO_ROOT).as_posix()}:{self.line}"

    def format(self) -> str:
        return f"{self.key}: {self.message}"


@dataclass
class Guard:
    name: str
    description: str
    check: Callable[[], list[Violation]]
    fix_hint: str = ""
    baselined: list[str] = field(default_factory=list)

    @property
    def baseline_path(self) -> Path:
        return BASELINE_DIR / f"{self.name.replace('.', '__')}.txt"

    def load_baseline(self) -> set[str]:
        if not self.baseline_path.exists():
            return set()
        keys: set[str] = set()
        for raw in self.baseline_path.read_text(encoding="utf-8").splitlines():
            line = raw.split("#", 1)[0].strip()
            if line:
                keys.add(line)
        return keys

    def save_baseline(self, keys: Iterable[str]) -> None:
        sorted_keys = sorted(set(keys))
        BASELINE_DIR.mkdir(parents=True, exist_ok=True)
        header = (
            "# Auto-generated by scripts/quality_gate.py --update-baseline.\n"
            "# Each line is a tolerated <relpath>:<lineno> match for this guard.\n"
            "# Reviewed in PR; remove entries as the code is cleaned up.\n"
        )
        self.baseline_path.write_text(
            header + "\n".join(sorted_keys) + ("\n" if sorted_keys else ""),
            encoding="utf-8",
        )


# ── File walking helpers ─────────────────────────────────────────────────────

_EXCLUDE_DIR_NAMES = {
    "node_modules", ".venv", "venv", "__pycache__", "dist", "build",
    ".pytest_cache", ".mypy_cache", ".ruff_cache", "htmlcov",
    "playwright-report", "test-results", "target", ".git",
}


def iter_files(root: Path, suffixes: tuple[str, ...]) -> Iterable[Path]:
    """Yield files under ``root`` matching any of ``suffixes``,
    skipping vendored / generated directories."""
    if not root.exists():
        return
    for path in root.rglob("*"):
        if path.is_dir():
            continue
        if any(part in _EXCLUDE_DIR_NAMES for part in path.parts):
            continue
        if path.suffix in suffixes:
            yield path


def grep_lines(path: Path, pattern: re.Pattern[str]) -> list[tuple[int, str]]:
    try:
        text = path.read_text(encoding="utf-8")
    except (UnicodeDecodeError, OSError):
        return []
    out: list[tuple[int, str]] = []
    for i, line in enumerate(text.splitlines(), start=1):
        if pattern.search(line):
            out.append((i, line))
    return out


def python_string_lines(path: Path) -> set[int]:
    """Return the set of 1-indexed line numbers that fall entirely
    inside a string literal (including docstrings + triple-quoted
    blocks). Used to skip pattern matches that occur in prose."""
    try:
        text = path.read_text(encoding="utf-8")
    except (UnicodeDecodeError, OSError):
        return set()
    in_string: set[int] = set()
    try:
        for tok in tokenize.generate_tokens(io.StringIO(text).readline):
            if tok.type == tokenize.STRING:
                (start_line, _), (end_line, _) = tok.start, tok.end
                for ln in range(start_line, end_line + 1):
                    in_string.add(ln)
    except (tokenize.TokenizeError, IndentationError, SyntaxError):
        # Tokenizer is best-effort — broken files surface in pytest/ruff,
        # not here. Falling back to "no string lines" means we may
        # double-count one or two false positives in pathological files.
        return set()
    return in_string


# ── Backend guards ───────────────────────────────────────────────────────────

_PRINT_RE = re.compile(r"^\s*print\s*\(")


def _backend_no_print() -> list[Violation]:
    """``print()`` in app code leaks to stdout instead of structlog;
    structlog is the only allowed log path so trace correlation +
    PII redaction stay intact."""
    root = REPO_ROOT / "backend" / "app"
    violations: list[Violation] = []
    for path in iter_files(root, (".py",)):
        for ln, _ in grep_lines(path, _PRINT_RE):
            violations.append(Violation(
                path, ln,
                "print() in backend/app/ — use structlog (logger.info / .warning / .error)",
            ))
    return violations


_DIRECT_TRIAGE_RE = re.compile(
    r"\brun_triage_agent\s*\(|"
    r"\bRulesEngine\s*\(\s*\)\s*\.classify_test\s*\(|"
    r"\bMLClassifier\s*\(\s*\)\s*\.classify\s*\("
)
# These two files own the dispatch and are allowed to call engines directly.
_ANALYSIS_ROUTER_ALLOWLIST = {
    "backend/app/services/analysis_router.py",
    "backend/app/services/agent.py",   # defines run_triage_agent itself
}


def _backend_analysis_router_bypass() -> list[Violation]:
    """``analysis_router.classify_test()`` is the single dispatcher for
    the four analysis modes. Direct calls to ``run_triage_agent()`` or
    the engines bypass mode resolution, fallback, and routing metadata,
    so reports lose decision traceability."""
    violations: list[Violation] = []
    for path in iter_files(REPO_ROOT / "backend" / "app", (".py",)):
        rel = path.relative_to(REPO_ROOT).as_posix()
        if rel in _ANALYSIS_ROUTER_ALLOWLIST:
            continue
        string_lines = python_string_lines(path)
        for ln, line in grep_lines(path, _DIRECT_TRIAGE_RE):
            if ln in string_lines:
                continue
            stripped = line.strip()
            if stripped.startswith("#"):
                continue
            violations.append(Violation(
                path, ln,
                "direct analysis-engine call — route through "
                "services.analysis_router.classify_test()",
            ))
    return violations


_FINALIZE_PATTERN = re.compile(r"\bfinalize_run\s*\(")
# Files that legitimately commit TestCase rows AND must call finalize_run
# afterwards. Adding a new such file requires adding it here (forcing review).
_INGESTION_OWNERS = (
    "backend/app/services/ingestion_pipeline.py",
    "backend/app/worker/tasks.py",
)


def _backend_finalize_run_wired() -> list[Violation]:
    """Any code path that commits TestCase rows must call
    ``ingestion_pipeline.finalize_run`` to drive suite membership +
    auto-tag + AI-pipeline. Otherwise ``/suites`` ends up empty while
    ``/runs`` is populated (the bug we hit on 2026-05-16)."""
    violations: list[Violation] = []
    for rel in _INGESTION_OWNERS:
        path = REPO_ROOT / rel
        if not path.exists():
            violations.append(Violation(
                path, 0,
                f"expected ingestion owner missing: {rel}",
            ))
            continue
        text = path.read_text(encoding="utf-8")
        if not _FINALIZE_PATTERN.search(text):
            violations.append(Violation(
                path, 0,
                "ingestion owner does not call finalize_run() — "
                "/suites will be empty for runs persisted here",
            ))
    return violations


_PII_RAW_LOG_RE = re.compile(
    # Looks for logger.* calls whose first kwarg references a likely
    # PII column without going through privacy_service. Coarse — we
    # baseline existing matches and refuse new ones.
    r"logger\.\w+\([^)]*\b(email|password|user_email|api_key|raw_key)\b\s*=",
)


def _backend_pii_log_redaction() -> list[Violation]:
    """Structlog calls that pass an obvious PII column verbatim. The
    rule is: route through ``privacy_service.sanitize_for_logging``
    so PII never reaches logs unredacted."""
    violations: list[Violation] = []
    for path in iter_files(REPO_ROOT / "backend" / "app", (".py",)):
        if "privacy_service.py" in path.as_posix():
            continue
        for ln, _ in grep_lines(path, _PII_RAW_LOG_RE):
            violations.append(Violation(
                path, ln,
                "logger call references PII verbatim — sanitize via "
                "services.privacy_service.sanitize_for_logging()",
            ))
    return violations


# Modules using structlog (``logger = structlog.get_logger(...)``).
# structlog's BoundLogger.warning/info/error has signature
# ``(event, **kwargs)`` — it does NOT accept stdlib-style positional
# args after the event string. Calls like
# ``logger.warning("foo: %s", exc)`` blow up with ``TypeError:
# BoundLoggerBase._proxy_to_logger() takes from 2 to 3 positional
# arguments but 4 were given`` the moment they fire — and when they
# fire from inside an ``except`` block on a request path, the
# TypeError escapes the handler and 500s the endpoint.
# Reference incident: 2026-05-18 ``/runs/compare/latest`` was 500-ing
# every call because ``run_compare_agent.py:82`` had this pattern and
# Ollama was unreachable (so the except handler fired). See
# ``memory/feedback_structlog_positional_args.md``.
_STRUCTLOG_LOGGER_RE = re.compile(
    r"\blogger\s*=\s*structlog\.get_logger",
)
_STRUCTLOG_POSITIONAL_RE = re.compile(
    # ``logger.<level>("…%X…", arg)`` — format-string + positional arg.
    # Allows ``%s``, ``%d``, ``%r``, ``%f``, ``%!s``.
    r'logger\.(warning|info|error|debug|exception|critical)\(\s*'
    r'["\'][^"\']*%[sdrf!][^"\']*["\']\s*,\s*[^)=]',
)


def _backend_structlog_positional_args() -> list[Violation]:
    """structlog BoundLogger doesn't accept stdlib-style positional args.

    Walk modules that bind a structlog logger and flag every call site
    using ``%s``-format + positional arguments. The baseline tolerates
    the 44 pre-existing call sites; new ones fail CI loudly.

    Fix at the call site: replace
    ``logger.warning("X failed: %s", exc)`` with
    ``logger.warning("X_failed", error=str(exc))``.
    """
    violations: list[Violation] = []
    for path in iter_files(REPO_ROOT / "backend" / "app", (".py",)):
        try:
            text = path.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        if not _STRUCTLOG_LOGGER_RE.search(text):
            # Module uses stdlib logging (or no logger at all) — the
            # positional-arg pattern is fine there. Skip.
            continue
        for ln, line in grep_lines(path, _STRUCTLOG_POSITIONAL_RE):
            stripped = line.strip()
            if stripped.startswith("#"):
                continue
            violations.append(Violation(
                path, ln,
                "structlog logger called with positional %s args — use "
                "kwargs (logger.warning(\"event_name\", error=str(exc)))",
            ))
    return violations


# ── Audit-table write discipline ─────────────────────────────────────────────
#
# The four models below document themselves as *append-only*. Nothing in the
# database enforces that: the entire migration set contains exactly one
# trigger (the search-vector trigger in ``0001``), no grants are restricted,
# and no store is WORM. **This guard is the enforcement** — it is what makes
# those docstrings true rather than aspirational, in the house style (a guard,
# not a promise).
#
# Rule: application code under ``backend/app/`` may INSERT audit rows and read
# them. It may never UPDATE one, and may never DELETE one outside the single
# allowlisted deleter below.
_AUDIT_MODELS = frozenset({
    "AccessAuditLog",      # access_audit_logs
    "IdentityEvent",       # identity_events
    "SettingsAuditLog",    # settings_audit_log
    "TestCaseAuditLog",    # test_case_audit_logs
})
_AUDIT_TABLES = (
    "access_audit_logs",
    "identity_events",
    "settings_audit_log",
    "test_case_audit_logs",
)

# ``services/retention_service.py`` is the ONE legitimate deleter. US-11.4
# gives every project an ``audit_days`` clock (floor 365 d, default 2555 ≈ 7 y,
# validated >= ``runs_days``) and the purge deletes ``access_audit_logs`` +
# ``test_case_audit_logs`` past it. That is deliberate, opt-in (policy
# ``enabled``), preview-able, and self-audited — every execute-mode purge
# writes its own ``settings_audit_log`` row. It is precisely why the models say
# "append-only", not "immutable". The allowlist covers DELETE only: even the
# retention service may not UPDATE an audit row.
_AUDIT_DELETE_ALLOWLIST = {
    "backend/app/services/retention_service.py",
}

_AUDIT_TABLE_ALT = "|".join(_AUDIT_TABLES)
_AUDIT_RAW_SQL_UPDATE_RE = re.compile(
    rf"\bupdate\s+(?:only\s+)?(?:public\.)?[\"`]?(?:{_AUDIT_TABLE_ALT})\b",
    re.IGNORECASE,
)
_AUDIT_RAW_SQL_DELETE_RE = re.compile(
    rf"\b(?:delete\s+from|truncate(?:\s+table)?)\s+(?:only\s+)?(?:public\.)?"
    rf"[\"`]?(?:{_AUDIT_TABLE_ALT})\b",
    re.IGNORECASE,
)


def _audit_call_name(func: ast.AST) -> str:
    """Terminal callable name — ``update`` for both ``update(X)`` and
    ``sa.update(X)`` / ``db.query(X).update(...)``."""
    if isinstance(func, ast.Name):
        return func.id
    if isinstance(func, ast.Attribute):
        return func.attr
    return ""


def _audit_referenced_names(node: ast.AST) -> set[str]:
    return {n.id for n in ast.walk(node) if isinstance(n, ast.Name)}


def _audit_scope_nodes(scope: ast.AST) -> list[ast.AST]:
    """Every node belonging to one lexical scope.

    Nested ``def`` / ``class`` / ``lambda`` bodies are excluded — they are
    analysed as scopes of their own, so a local called ``row`` in one function
    can never be confused with a ``row`` in another (the bug that made a
    module-wide pass flag ``retention_service.upsert_policy``).
    """
    out: list[ast.AST] = []
    stack = list(ast.iter_child_nodes(scope))
    while stack:
        node = stack.pop()
        out.append(node)
        if isinstance(
            node,
            (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef, ast.Lambda),
        ):
            continue
        stack.extend(ast.iter_child_nodes(node))
    return out


def _audit_scopes(tree: ast.AST) -> list[list[ast.AST]]:
    scopes = [_audit_scope_nodes(tree)]
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.Lambda)):
            scopes.append(_audit_scope_nodes(node))
    return scopes


def _audit_row_names(nodes: list[ast.AST]) -> set[str]:
    """Names in one scope bound to a **fetched** audit row (or a container).

    A freshly constructed row (``row = SettingsAuditLog(...)``) is excluded on
    purpose: mutating its attributes before ``flush`` is still one INSERT, and
    that is the normal write path. Anything else that mentions an audit model
    (a ``select(...)`` result, a ``scalars().all()`` list, a loop variable over
    either) is treated as an already-persisted row, so attribute stores on it
    are UPDATEs.
    """
    names: set[str] = set()
    # Re-run until stable so ``rows = select(...)`` → ``for row in rows:``
    # propagates through intermediate bindings.
    for _ in range(4):
        before = len(names)
        for node in nodes:
            if isinstance(node, (ast.Assign, ast.AnnAssign)):
                value = node.value
                if value is None:
                    continue
                referenced = _audit_referenced_names(value)
                if not (referenced & _AUDIT_MODELS or referenced & names):
                    continue
                if (
                    isinstance(value, ast.Call)
                    and _audit_call_name(value.func) in _AUDIT_MODELS
                ):
                    continue  # construction — an INSERT being staged
                targets = (
                    node.targets if isinstance(node, ast.Assign) else [node.target]
                )
                for target in targets:
                    if isinstance(target, ast.Name):
                        names.add(target.id)
            elif isinstance(node, (ast.For, ast.AsyncFor)):
                referenced = _audit_referenced_names(node.iter)
                if (referenced & _AUDIT_MODELS or referenced & names) and isinstance(
                    node.target, ast.Name
                ):
                    names.add(node.target.id)
        if len(names) == before:
            break
    return names


def _backend_audit_write_discipline(root: Optional[Path] = None) -> list[Violation]:
    """Audit tables are append-only — enforce it, don't just document it.

    ``settings_audit_log``, ``access_audit_logs``, ``test_case_audit_logs`` and
    ``identity_events`` have no triggers, no restricted grants and no WORM
    storage behind them. This guard fails CI when application code:

    * builds an UPDATE against an audit model (``update(AccessAuditLog)``,
      ``sa.update(...)``, ``db.query(...).update(...)``),
    * assigns to an attribute of a **fetched** audit row (or calls
      ``setattr`` / ``db.delete`` on one),
    * builds a DELETE against an audit model outside
      ``services/retention_service.py``,
    * embeds raw SQL that UPDATEs / DELETEs FROM / TRUNCATEs an audit table.

    Deliberate blind spots (written down so nobody trusts the guard past its
    edge): raw SQL whose table name is assembled at runtime (f-strings,
    concatenation); a mutation performed inside a generic helper that receives
    an audit row as a *parameter*, or inside a nested closure over an outer
    row — name binding within one scope is what we track; Alembic migrations,
    which are reviewed schema evolution and out of scope; and anything done
    outside the application (psql, a DBA, a restore, a backup rollback).
    """
    root = root or (REPO_ROOT / "backend" / "app")
    violations: list[Violation] = []
    for path in iter_files(root, (".py",)):
        try:
            text = path.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        if not any(model in text for model in _AUDIT_MODELS) and not any(
            table in text for table in _AUDIT_TABLES
        ):
            continue
        try:
            rel = path.relative_to(REPO_ROOT).as_posix()
        except ValueError:
            rel = path.as_posix()
        delete_allowed = rel in _AUDIT_DELETE_ALLOWLIST

        seen: set[tuple[int, str]] = set()

        def _flag(line: int, kind: str, message: str) -> None:
            if (line, kind) in seen:
                return
            seen.add((line, kind))
            violations.append(Violation(path, line, message))

        try:
            tree = ast.parse(text)
        except (SyntaxError, ValueError):
            tree = None

        for scope_nodes in _audit_scopes(tree) if tree is not None else []:
            fetched = _audit_row_names(scope_nodes)
            for node in scope_nodes:
                # (a) Core / ORM bulk constructs against an audit model.
                if isinstance(node, ast.Call):
                    name = _audit_call_name(node.func)
                    arg_hits = (
                        _audit_referenced_names(node.args[0]) & _AUDIT_MODELS
                        if node.args
                        else set()
                    )
                    chain_hits: set[str] = set()
                    if isinstance(node.func, ast.Attribute):
                        chain_hits = (
                            _audit_referenced_names(node.func.value) & _AUDIT_MODELS
                        )
                    if name == "update" and (arg_hits or chain_hits):
                        _flag(
                            node.lineno, "update",
                            "UPDATE against an audit table "
                            f"({', '.join(sorted(arg_hits or chain_hits))}) — audit "
                            "rows are append-only; write a new row instead",
                        )
                    elif name == "delete" and (arg_hits or chain_hits):
                        if not delete_allowed:
                            _flag(
                                node.lineno, "delete",
                                "DELETE against an audit table "
                                f"({', '.join(sorted(arg_hits or chain_hits))}) — the "
                                "retention purge (services/retention_service.py) is "
                                "the only allowed deleter",
                            )
                    elif (
                        name == "setattr"
                        and node.args
                        and isinstance(node.args[0], ast.Name)
                        and node.args[0].id in fetched
                    ):
                        _flag(
                            node.lineno, "update",
                            f"setattr on fetched audit row {node.args[0].id!r} — "
                            "audit rows are append-only",
                        )
                    elif (
                        name == "delete"
                        and len(node.args) == 1
                        and isinstance(node.args[0], ast.Name)
                        and node.args[0].id in fetched
                        and not delete_allowed
                    ):
                        _flag(
                            node.lineno, "delete",
                            f"session delete of fetched audit row "
                            f"{node.args[0].id!r} — only the retention purge may "
                            "delete audit rows",
                        )
                # (b) Attribute store on a fetched audit row.
                targets: list[ast.AST] = []
                if isinstance(node, ast.Assign):
                    targets = list(node.targets)
                elif isinstance(node, (ast.AugAssign, ast.AnnAssign)):
                    targets = [node.target]
                for target in targets:
                    if (
                        isinstance(target, ast.Attribute)
                        and isinstance(target.value, ast.Name)
                        and target.value.id in fetched
                    ):
                        _flag(
                            node.lineno, "update",
                            f"attribute assignment on fetched audit row "
                            f"{target.value.id}.{target.attr} — audit rows are "
                            "append-only; write a new row instead",
                        )

        # (c) Raw SQL embedded as a literal.
        for ln, line in grep_lines(path, _AUDIT_RAW_SQL_UPDATE_RE):
            if line.strip().startswith("#"):
                continue
            _flag(ln, "update", "raw SQL UPDATE of an audit table — append-only")
        for ln, line in grep_lines(path, _AUDIT_RAW_SQL_DELETE_RE):
            if line.strip().startswith("#") or delete_allowed:
                continue
            _flag(
                ln, "delete",
                "raw SQL DELETE/TRUNCATE of an audit table — only the retention "
                "purge (services/retention_service.py) may delete audit rows",
            )
    return violations


# ── Frontend guards ──────────────────────────────────────────────────────────

_CLIPBOARD_RE = re.compile(r"navigator\.clipboard\.writeText\b")
_CLIPBOARD_OWNER = "frontend/src/utils/clipboard.ts"


def _frontend_clipboard_util() -> list[Violation]:
    """``navigator.clipboard.writeText`` is gated to secure contexts and
    silently throws on HTTP origins like the homelab. Every copy must
    route through ``utils/clipboard.copyTextToClipboard`` which has a
    ``document.execCommand`` fallback."""
    violations: list[Violation] = []
    root = REPO_ROOT / "frontend" / "src"
    for path in iter_files(root, (".ts", ".tsx")):
        rel = path.relative_to(REPO_ROOT).as_posix()
        if rel == _CLIPBOARD_OWNER:
            continue
        for ln, _ in grep_lines(path, _CLIPBOARD_RE):
            violations.append(Violation(
                path, ln,
                "navigator.clipboard.writeText — use "
                "copyTextToClipboard from @/utils/clipboard "
                "(fails silently on HTTP origins)",
            ))
    return violations


_HEDGING_BLOCK_COMMENT_RE = re.compile(r"/\*.*?\*/", re.DOTALL)
_HEDGING_LINE_COMMENT_RE = re.compile(r"//.*$", re.MULTILINE)
_HEDGING_JSX_COMMENT_RE = re.compile(r"\{\s*/\*.*?\*/\s*\}", re.DOTALL)

# Verdict phrasings. Each entry is (pattern, why). They are deliberately
# narrow: they fire on copy that asserts the cause is KNOWN, and stay silent
# on hedged forms ("likely caused by", "suggested root cause", "suspects, not
# culprits") and on pipeline STAGE names ("Root Cause Analysis"), which name a
# stage rather than a conclusion.
_AI_HEDGING_PATTERNS: tuple[tuple[re.Pattern[str], str], ...] = (
    (
        re.compile(r"\broot cause\s*:", re.IGNORECASE),
        "a bare \"Root cause:\" label presents an AI suggestion as a verdict "
        "— use \"Suggested root cause\"",
    ),
    (
        re.compile(r"\broot cause summary\b", re.IGNORECASE),
        "\"Root Cause Summary\" asserts the cause is known — say "
        "\"Suggested root cause\"",
    ),
    (
        re.compile(r"\bthe (?:root )?cause (?:is|was)\b", re.IGNORECASE),
        "\"the cause is …\" states an AI inference as fact — hedge it "
        "(\"the suggested cause\", \"likely\")",
    ),
    (
        re.compile(r"\b(?:is|was|are|were)\s+caused by\b", re.IGNORECASE),
        "\"is caused by\" asserts causation the pipeline cannot establish — "
        "use \"likely caused by\" or \"consistent with\"",
    ),
)


def _strip_ts_comments(text: str) -> str:
    """Blank out comments while preserving line numbering.

    Copy lives in JSX text and string literals; comments legitimately quote
    the very phrasings this guard bans (this file's own docstring does).
    Newlines are preserved so reported line numbers stay accurate.
    """
    def _blank(match: re.Match[str]) -> str:
        return "\n" * match.group(0).count("\n")

    text = _HEDGING_JSX_COMMENT_RE.sub(_blank, text)
    text = _HEDGING_BLOCK_COMMENT_RE.sub(_blank, text)
    return _HEDGING_LINE_COMMENT_RE.sub("", text)


def _frontend_ai_output_hedging() -> list[Violation]:
    """AI output is a suggestion for a human to confirm — never a verdict.

    US-15.1 put every AI-produced conclusion behind the shared
    ``components/ai/AISuggestion`` trust chrome ("AI-suggested" badge,
    confidence + calibration basis, routing provenance, evidence,
    confirm/correct). Chrome is worthless if the copy inside it still reads
    as fact, so this guard fails CI on the verdict phrasings that keep
    creeping back into rendered strings: a bare ``Root cause:`` label,
    ``Root Cause Summary``, ``the cause is …``, and ``is caused by``.

    Hedged phrasings pass on purpose — "Suggested root cause", "likely caused
    by", "Suspects, not culprits" — as do pipeline STAGE names such as "Root
    Cause Analysis", which name a stage of the pipeline rather than a
    conclusion about a failure.

    Deliberate blind spots (written down so nobody trusts the guard past its
    edge):

    * **Runtime-assembled copy.** Template literals interpolating variables,
      strings built by concatenation, and anything looked up from a map at
      render time are matched only if the banned words survive verbatim on
      one source line.
    * **Backend- and model-authored text.** The single largest source of
      un-hedged assertions is the LLM's own ``root_cause_summary`` prose,
      which is data, not source. API field names (``root_cause``,
      ``root_cause_summary``) are out of scope by design — renaming the wire
      contract is not a copy fix.
    * **Naive comment stripping.** ``//`` inside a string literal (a URL, a
      regex) truncates the rest of that line, so a banned phrase after it on
      the same line goes unseen.
    * **Semantics, not spelling.** A sentence that asserts causation without
      these exact words — "the culprit is", "blame:", "this broke because" —
      sails straight through. The guard catches the four phrasings we have
      actually shipped, not the concept.
    * **Tests and e2e specs** are exempt: they assert on copy, including copy
      they are proving is absent.
    """
    violations: list[Violation] = []
    root = REPO_ROOT / "frontend" / "src"
    for path in iter_files(root, (".ts", ".tsx")):
        name = path.name
        if ".test." in name or ".spec." in name:
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        stripped = _strip_ts_comments(text)
        for lineno, line in enumerate(stripped.splitlines(), start=1):
            for pattern, why in _AI_HEDGING_PATTERNS:
                if pattern.search(line):
                    violations.append(Violation(path, lineno, why))
    return violations


_ALL_PROJECTS_LITERAL_RE = re.compile(
    # Look for "'all'" / '"all"' being assigned to a project_id-shaped
    # variable / param. Coarse but matches the failure mode from
    # CLAUDE.md pitfall #1.
    r"project_?[Ii]d\s*[:=]\s*['\"]all['\"]"
)


def _frontend_all_projects_literal() -> list[Violation]:
    """``ALL_PROJECTS_ID = 'all'`` is a frontend-only sentinel. Sending
    the literal string ``'all'`` to the backend as a UUID returns 422
    (no project filter is applied). Convert to ``null`` before the
    API call."""
    violations: list[Violation] = []
    root = REPO_ROOT / "frontend" / "src"
    for path in iter_files(root, (".ts", ".tsx")):
        for ln, _ in grep_lines(path, _ALL_PROJECTS_LITERAL_RE):
            violations.append(Violation(
                path, ln,
                "literal 'all' assigned to project_id — backend wants null",
            ))
    return violations


_AXIOS_CREATE_RE = re.compile(r"\baxios\.create\s*\(")
_AXIOS_OWNER = "frontend/src/services/api.ts"


_REFRESH_LITERAL_RE = re.compile(r"refreshInterval:\s*([0-9_]+)")


def _frontend_refresh_intervals_from_config() -> list[Violation]:
    """SWR poll cadences must come from config/refreshIntervals.ts.

    That file states "All hooks should import from here — never hardcode
    intervals" and defines four tiers. Nothing enforced it, and the drift ran
    2:1 against the rule: 10 hooks hardcoded 30 literals while 5 imported the
    tiers. Two hooks polled at 2s and 3s — faster than REALTIME (5s), which the
    config assigns to "live execution dashboards, agent pipelines", i.e. exactly
    those hooks.

    A scattered literal is not just style: poll cadence is server load, and
    nobody can see the total request rate when it is spread across ten files.

    ``refreshInterval: 0`` is allowed — that is SWR's "polling disabled", not a
    cadence. The SWR 2 function form is allowed too (see useFixer), since a
    dynamic interval cannot be a constant.
    """
    violations: list[Violation] = []
    root = REPO_ROOT / "frontend" / "src" / "hooks"
    if not root.exists():
        return violations
    for path in iter_files(root, (".ts", ".tsx")):
        if path.name.endswith((".test.ts", ".test.tsx")):
            continue
        for ln, line in grep_lines(path, _REFRESH_LITERAL_RE):
            m = _REFRESH_LITERAL_RE.search(line)
            if not m:
                continue
            if int(m.group(1).replace("_", "")) == 0:
                continue
            violations.append(Violation(
                path, ln,
                f"hardcoded refreshInterval {m.group(1)} — import a tier from "
                f"@/config/refreshIntervals so the app's total poll rate is "
                f"visible in one place",
            ))
    return violations


def _frontend_single_axios() -> list[Violation]:
    """One Axios instance owns auth refresh + 401 queue. A second
    instance silently bypasses the refresh interceptor, so 401s
    surface to the UI instead of getting transparently retried."""
    violations: list[Violation] = []
    root = REPO_ROOT / "frontend" / "src"
    for path in iter_files(root, (".ts", ".tsx")):
        rel = path.relative_to(REPO_ROOT).as_posix()
        if rel == _AXIOS_OWNER:
            continue
        for ln, _ in grep_lines(path, _AXIOS_CREATE_RE):
            violations.append(Violation(
                path, ln,
                "second axios.create() — import the shared instance "
                "from @/services/api (or use getData/postData helpers)",
            ))
    return violations


_FETCH_IN_PAGE_RE = re.compile(r"\b(fetch|axios)\s*\(")
_PAGE_FILE_RE = re.compile(r"frontend[\\/]src[\\/]pages[\\/]")


def _frontend_swr_only_fetching() -> list[Violation]:
    """Pages must read through an SWR hook so refresh / dedupe /
    refetch-on-project-switch all work consistently. Raw ``fetch`` or
    ``axios`` inside a page is a regression — the page won't refresh
    when the user changes project."""
    violations: list[Violation] = []
    root = REPO_ROOT / "frontend" / "src" / "pages"
    for path in iter_files(root, (".tsx",)):
        if path.name.endswith(".test.tsx"):
            continue
        for ln, line in grep_lines(path, _FETCH_IN_PAGE_RE):
            # Skip obvious benign cases (createObjectURL fetcher refs, etc.).
            if "URL.createObjectURL" in line or "window.fetch" in line:
                continue
            violations.append(Violation(
                path, ln,
                "raw fetch/axios in a page — use a hook in src/hooks/ "
                "wrapping SWR or useProjectScopedSWR",
            ))
    return violations


# ── Database guards ──────────────────────────────────────────────────────────

_DOWN_REV_RE = re.compile(r"^down_revision\s*=\s*['\"]([^'\"]+)['\"]", re.MULTILINE)
_REV_RE = re.compile(r"^revision\s*=\s*['\"]([^'\"]+)['\"]", re.MULTILINE)


def _database_single_alembic_head() -> list[Violation]:
    """Multiple Alembic heads block ``alembic upgrade head`` and break
    container startup. The fix is to pick a fresh ``down_revision``
    when generating a migration — see the ``feedback_alembic_head_conflicts``
    memory."""
    versions = REPO_ROOT / "backend" / "migrations" / "versions"
    if not versions.exists():
        return []
    revisions: dict[str, Path] = {}
    children: dict[str, list[str]] = {}
    for path in iter_files(versions, (".py",)):
        text = path.read_text(encoding="utf-8")
        rev_m = _REV_RE.search(text)
        down_m = _DOWN_REV_RE.search(text)
        if not rev_m:
            continue
        rev = rev_m.group(1)
        revisions[rev] = path
        if down_m:
            children.setdefault(down_m.group(1), []).append(rev)
    # A head is a revision with no children.
    heads = [r for r in revisions if r not in children]
    if len(heads) <= 1:
        return []
    return [
        Violation(
            revisions[h], 0,
            f"multiple Alembic heads detected: {sorted(heads)} — "
            "re-base your migration's down_revision onto the current head",
        )
        for h in heads
    ]


_MIGRATION_DOWN_RE = re.compile(r"^def\s+downgrade\s*\(", re.MULTILINE)


def _database_downgrade_implemented() -> list[Violation]:
    """Every migration must implement ``downgrade()``. Empty stubs
    block rollback in incident response."""
    versions = REPO_ROOT / "backend" / "migrations" / "versions"
    if not versions.exists():
        return []
    violations: list[Violation] = []
    for path in iter_files(versions, (".py",)):
        text = path.read_text(encoding="utf-8")
        if not _MIGRATION_DOWN_RE.search(text):
            violations.append(Violation(
                path, 0, "missing downgrade() function",
            ))
            continue
        # Detect ``def downgrade(): pass`` / ``def downgrade(): ...``
        # bodies — same effect as missing. Cheap heuristic that skips
        # docstrings + comments so a downgrade that only contains a
        # ``"""no-op: index drop is implicit"""`` docstring still counts
        # as deliberate (the author has explained it).
        after = text.split("def downgrade", 1)[1].split("\ndef ", 1)[0]
        body_lines = after.splitlines()[1:]
        in_docstring = False
        has_explanation = False  # docstring OR inline comment
        meaningful: list[str] = []
        for raw in body_lines:
            s = raw.strip()
            if not s:
                continue
            if in_docstring:
                has_explanation = True
                if s.endswith('"""') or s.endswith("'''"):
                    in_docstring = False
                continue
            if s.startswith('"""') or s.startswith("'''"):
                has_explanation = True
                # Single-line docstring closes on the same line; multi-
                # line stays open until we hit a closing triple-quote.
                if not (len(s) >= 6 and (s.endswith('"""') or s.endswith("'''"))):
                    in_docstring = True
                continue
            if s.startswith("#"):
                # Accept comments as no-op explanations too — many
                # migrations explain "intentional no-op" inline rather
                # than via docstring (e.g. 0045_clean_user_role_strings).
                has_explanation = True
                continue
            meaningful.append(s)
        # Empty body = no docstring, no comments, no statements (or
        # only ``pass`` / ``...``). A docstring or inline comment is
        # treated as a deliberate no-op explanation and passes.
        is_empty = not meaningful or all(s in {"pass", "..."} for s in meaningful)
        if is_empty and not has_explanation:
            violations.append(Violation(
                path, 0,
                "downgrade() is empty — implement reverse of upgrade() "
                "or add a docstring explaining why rollback is unsupported",
            ))
    return violations


# ── Agentic AI guards ────────────────────────────────────────────────────────

_BASE_AGENT_RE = re.compile(r"class\s+\w+\s*\(\s*BaseAgent\s*[,)]")
_SUPPORT_AGENT_FILES = {
    # Support modules in app/agents/ that are NOT agent implementations.
    "__init__.py", "state.py", "workflow.py", "conversation.py", "base.py",
    # consistency.py holds the AIQ-P2 self-critique Pydantic models + pure-local
    # checker functions; it has no agent class and no observability contract.
    "consistency.py",
    # evidence.py holds the AIQ-P3 EvidenceRef model + aggregate_confidence
    # helper; it is a pure-local scoring utility with no agent class and no
    # observability contract.
    "evidence.py",
    # Fixer (AI-2) support modules — NOT LangGraph pipeline agents. runners.py
    # holds the sandbox ValidationRunner executors (subprocess/HTTP), pipeline.py
    # holds pure stage helpers (candidate selection, glob rejection, PR opener,
    # outcome poller). Their audit surface is the fix_attempts rows + the
    # agent_runs ledger, not the BaseAgent stage/decision contract.
    "runners.py", "pipeline.py",
}


def _agents_base_agent_subclass() -> list[Violation]:
    """Every agent implementation in ``backend/app/agents/`` must
    subclass ``BaseAgent`` so its stages, decision log, and OTEL
    spans land in the standard tables. Standalone classes silently
    skip the observability contract."""
    root = REPO_ROOT / "backend" / "app" / "agents"
    violations: list[Violation] = []
    for path in iter_files(root, (".py",)):
        if path.name in _SUPPORT_AGENT_FILES:
            continue
        text = path.read_text(encoding="utf-8")
        if "class " not in text:
            continue
        if not _BASE_AGENT_RE.search(text):
            violations.append(Violation(
                path, 0,
                "agent class does not subclass BaseAgent — "
                "stage tracking + decision_log + OTEL spans will be missed",
            ))
    return violations


def _agents_log_decision_present() -> list[Violation]:
    """Every BaseAgent subclass should call ``self.log_decision(...)``
    at least once. A subclass without a single decision log entry
    produces an empty ``AgentStageResult.decision_log`` and breaks
    the UI's "why did the agent do X" surface."""
    root = REPO_ROOT / "backend" / "app" / "agents"
    violations: list[Violation] = []
    for path in iter_files(root, (".py",)):
        if path.name in _SUPPORT_AGENT_FILES:
            continue
        text = path.read_text(encoding="utf-8")
        if not _BASE_AGENT_RE.search(text):
            continue
        if "log_decision" not in text:
            violations.append(Violation(
                path, 0,
                "BaseAgent subclass missing self.log_decision(...) — "
                "every non-trivial branch should be logged",
            ))
    return violations


# ── Homelab guards ───────────────────────────────────────────────────────────

_HOMELAB_OVERLAY_REL = "k8s/overlays/homelab/kustomization.yaml"
# Images whose ``newTag:`` must remain the placeholder at rest. Mirrors
# the ``images:`` block at the bottom of the homelab overlay; if a new
# locally-built image is added there, append it here too.
_HOMELAB_PINNED_IMAGES = (
    "testlookup/backend",
    "testlookup/frontend",
    "testlookup/mcp",
)
_HOMELAB_PLACEHOLDER = "BUILD_TAG_PLACEHOLDER"

# Match a kustomize ``images:`` entry block:
#   - name: testlookup/backend
#     newName: registry.local:30500/testlookup/backend
#     newTag: BUILD_TAG_PLACEHOLDER
# Captures the image name and the newTag value on the line that follows
# (one or more lines down). Tolerant of intervening ``newName:`` /
# blank / comment lines so the layout in the overlay can evolve without
# breaking the guard. The non-greedy ``.*?`` + DOTALL is bounded by the
# next ``- name:`` or end-of-string via a positive lookahead — we want
# only the ``newTag:`` belonging to *this* image, not the one for the
# next image in the list.
_HOMELAB_IMAGE_BLOCK_RE = re.compile(
    r"-\s*name:\s*(?P<name>\S+)"
    r"(?P<body>.*?)"
    r"(?=^\s*-\s*name:|\Z)",
    re.DOTALL | re.MULTILINE,
)
_HOMELAB_NEW_TAG_RE = re.compile(
    r"^\s*newTag:\s*(?P<tag>\S+)\s*$",
    re.MULTILINE,
)


def _homelab_build_tag_placeholder() -> list[Violation]:
    """The homelab overlay's ``newTag:`` for every locally-built image
    must equal ``BUILD_TAG_PLACEHOLDER`` at rest. ``deploy-homelab.sh``
    substitutes it in-place per-deploy and ``trap``s a restore on exit,
    but a hard kill (SIGKILL, runner OOM, power loss between the sed
    and the restore) can leave a real timestamp committed by mistake.

    The existing ``k8s-image-pin-check`` CI guard already rejects the
    word ``latest``; this guard closes the matching hole for any other
    accidentally-committed substituted tag (e.g. ``build-20260518-013421``).
    """
    path = REPO_ROOT / _HOMELAB_OVERLAY_REL
    if not path.exists():
        return []
    text = path.read_text(encoding="utf-8")

    # Build a name → (newTag value, line number) map by walking the
    # ``images:`` block entries. Line numbers are best-effort: we record
    # the line of the ``newTag:`` match so the failure points at the
    # exact offender, not the top of the file.
    line_offsets: list[int] = [0]
    running = 0
    for ch in text:
        if ch == "\n":
            line_offsets.append(running + 1)
        running += 1

    def char_to_line(offset: int) -> int:
        """1-indexed line number for a character offset."""
        # Linear scan is fine — overlay file is < 500 lines.
        for i, start in enumerate(line_offsets):
            if start > offset:
                return i
        return len(line_offsets)

    violations: list[Violation] = []
    seen: dict[str, tuple[str, int]] = {}
    for block in _HOMELAB_IMAGE_BLOCK_RE.finditer(text):
        name = block.group("name").strip()
        if name not in _HOMELAB_PINNED_IMAGES:
            continue
        tag_match = _HOMELAB_NEW_TAG_RE.search(block.group("body"))
        if not tag_match:
            # Missing newTag is a bug in the overlay shape — flag it so
            # nobody silently regresses to a floating tag.
            seen[name] = ("", char_to_line(block.start()))
            continue
        # Translate the match's offset back to the absolute file offset
        # so the line number points at the real ``newTag:`` line.
        abs_offset = block.start("body") + tag_match.start("tag")
        seen[name] = (tag_match.group("tag").strip(), char_to_line(abs_offset))

    for name in _HOMELAB_PINNED_IMAGES:
        entry = seen.get(name)
        if entry is None:
            violations.append(Violation(
                path, 0,
                f"homelab overlay missing 'images:' entry for {name!r} — "
                "every locally-built image must be pinned to "
                f"{_HOMELAB_PLACEHOLDER}",
            ))
            continue
        tag, line = entry
        if not tag:
            violations.append(Violation(
                path, line,
                f"{name!r} has no newTag — pin it to {_HOMELAB_PLACEHOLDER} "
                "so deploy-homelab.sh substitutes it per-deploy",
            ))
            continue
        if tag != _HOMELAB_PLACEHOLDER:
            violations.append(Violation(
                path, line,
                f"{name!r} newTag is {tag!r} — must be "
                f"{_HOMELAB_PLACEHOLDER}. A previous deploy-homelab.sh "
                "run was likely killed mid-deploy before its trap "
                "could restore the placeholder. Reset with: "
                f"git checkout -- {_HOMELAB_OVERLAY_REL}",
            ))
    return violations


def _agents_routing_metadata_populated() -> list[Violation]:
    """``analysis_router.classify_test`` must populate a ``_routing``
    dict on every return so per-test rows carry mode-used /
    fallback-from / fallback-reason. Without it, the UI cannot
    explain why a given test was classified by rules vs. LLM."""
    path = REPO_ROOT / "backend" / "app" / "services" / "analysis_router.py"
    if not path.exists():
        return []
    text = path.read_text(encoding="utf-8")
    if '"_routing"' not in text and "_routing'" not in text:
        return [Violation(
            path, 0,
            "analysis_router.classify_test does not assign _routing — "
            "decision traceability contract is broken",
        )]
    return []


# ── AI prompt-manifest guard (AI-F2) ─────────────────────────────────────────
# Every LLM prompt is registered in backend/app/services/prompt_registry.py
# (MCP templates in mcp/prompts/templates.py::PROMPT_TEMPLATES) and pinned —
# sha256(text)[:12] + version — in prompt_manifest.json. A prompt edit without
# a deliberate manifest bump fails here; a manifest bump without a fresh
# eval-gate attestation (prompt_manifest_eval.json) also fails here. This is
# the CI blocker that makes "no prompt change ships without an eval run" real.
# Stdlib-only mirror of app.services.prompt_registry's checks: sources are
# parsed via ast, never imported.

_PROMPT_REGISTRY_PATH = REPO_ROOT / "backend" / "app" / "services" / "prompt_registry.py"
_PROMPT_MANIFEST_PATH = REPO_ROOT / "backend" / "app" / "services" / "prompt_manifest.json"
_PROMPT_ATTESTATION_PATH = REPO_ROOT / "backend" / "app" / "services" / "prompt_manifest_eval.json"
_MCP_PROMPT_TEMPLATES_PATH = REPO_ROOT / "mcp" / "prompts" / "templates.py"
_PROMPT_HASH_LEN = 12
_PROMPT_ATTEST_HINT = (
    "cd backend && python -m app.services.prompt_registry --write-manifest && "
    "python -m app.services.prompt_registry --attest <change-id> "
    "(add --offline without a live DB)"
)


def _prompt_content_hash(text: str) -> str:
    """MUST mirror app.services.prompt_registry.content_hash."""
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:_PROMPT_HASH_LEN]


def _prompt_manifest_digest(prompts: dict) -> str:
    """MUST mirror app.services.prompt_registry.manifest_digest."""
    canonical = json.dumps(prompts, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def _extract_registry_prompts(path: Path) -> tuple[dict, list[tuple[int, str]]]:
    """``{id: {"version", "content_hash", "line"}}`` from ``_register(...)`` calls."""
    prompts: dict = {}
    problems: list[tuple[int, str]] = []
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"))
    except (OSError, SyntaxError, ValueError) as exc:
        return {}, [(0, f"cannot parse prompt registry: {exc}")]
    for node in ast.walk(tree):
        if not (
            isinstance(node, ast.Call)
            and isinstance(node.func, ast.Name)
            and node.func.id == "_register"
        ):
            continue
        try:
            pid = ast.literal_eval(node.args[0])
            version = int(ast.literal_eval(node.args[1]))
            text = ast.literal_eval(node.args[2])
        except (ValueError, TypeError, IndexError):
            problems.append((
                node.lineno,
                "_register(...) call is not fully literal — the manifest "
                "guard cannot hash it; keep prompt texts as plain string "
                "literals",
            ))
            continue
        prompts[pid] = {
            "version": version,
            "content_hash": _prompt_content_hash(str(text)),
            "line": node.lineno,
        }
    if not prompts and not problems:
        problems.append((0, "no _register(...) calls found in the prompt registry"))
    return prompts, problems


def _extract_mcp_prompts(path: Path) -> tuple[dict, list[tuple[int, str]]]:
    """``{id: {"version", "content_hash", "line"}}`` from ``PROMPT_TEMPLATES``."""
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"))
    except (OSError, SyntaxError, ValueError) as exc:
        return {}, [(0, f"cannot parse MCP prompt templates: {exc}")]
    templates: dict = {}
    versions: dict = {}
    line = 0
    for node in tree.body:
        if isinstance(node, ast.Assign):
            names = [t.id for t in node.targets if isinstance(t, ast.Name)]
            value = node.value
        elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            names = [node.target.id]
            value = node.value
        else:
            continue
        if value is None:
            continue
        try:
            if "PROMPT_TEMPLATES" in names:
                templates = dict(ast.literal_eval(value))
                line = node.lineno
            elif "PROMPT_TEMPLATE_VERSIONS" in names:
                versions = dict(ast.literal_eval(value))
        except (ValueError, TypeError):
            return {}, [(node.lineno, "PROMPT_TEMPLATES is not a literal dict")]
    if not templates:
        return {}, [(0, "no PROMPT_TEMPLATES dict found in MCP templates module")]
    return {
        pid: {
            "version": int(versions.get(pid, 1)),
            "content_hash": _prompt_content_hash(str(text)),
            "line": line,
        }
        for pid, text in templates.items()
    }, []


def _ai_prompt_manifest_sync(
    registry_path: Optional[Path] = None,
    manifest_path: Optional[Path] = None,
    attestation_path: Optional[Path] = None,
    mcp_path: Optional[Path] = None,
) -> list[Violation]:
    registry_path = registry_path or _PROMPT_REGISTRY_PATH
    manifest_path = manifest_path or _PROMPT_MANIFEST_PATH
    attestation_path = attestation_path or _PROMPT_ATTESTATION_PATH
    mcp_path = mcp_path or _MCP_PROMPT_TEMPLATES_PATH

    violations: list[Violation] = []

    current: dict = {}
    reg_prompts, reg_problems = _extract_registry_prompts(registry_path)
    for line, msg in reg_problems:
        violations.append(Violation(registry_path, line, msg))
    current.update({pid: (entry, registry_path) for pid, entry in reg_prompts.items()})

    if mcp_path.exists():
        mcp_prompts, mcp_problems = _extract_mcp_prompts(mcp_path)
        for line, msg in mcp_problems:
            violations.append(Violation(mcp_path, line, msg))
        current.update({pid: (entry, mcp_path) for pid, entry in mcp_prompts.items()})

    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        pinned = manifest["prompts"]
        assert isinstance(pinned, dict)
    except (OSError, ValueError, KeyError, AssertionError) as exc:
        violations.append(Violation(
            manifest_path, 0,
            f"prompt manifest missing/unreadable ({exc}) — {_PROMPT_ATTEST_HINT}",
        ))
        return violations

    for pid, (entry, src_path) in sorted(current.items()):
        pin = pinned.get(pid)
        if pin is None:
            violations.append(Violation(
                src_path, entry["line"],
                f"prompt {pid!r} is not pinned in the manifest — {_PROMPT_ATTEST_HINT}",
            ))
            continue
        if pin.get("content_hash") != entry["content_hash"]:
            violations.append(Violation(
                src_path, entry["line"],
                f"prompt {pid!r} text drifted from the manifest (hash "
                f"{entry['content_hash']} != pinned {pin.get('content_hash')}). "
                f"Bump its version, then: {_PROMPT_ATTEST_HINT}",
            ))
        elif pin.get("version") != entry["version"]:
            violations.append(Violation(
                src_path, entry["line"],
                f"prompt {pid!r} version {entry['version']} != pinned "
                f"{pin.get('version')} — {_PROMPT_ATTEST_HINT}",
            ))
    for pid in sorted(pinned):
        if pid not in current:
            violations.append(Violation(
                manifest_path, 0,
                f"manifest pins {pid!r} but no such prompt is registered "
                f"(stale entry) — {_PROMPT_ATTEST_HINT}",
            ))

    # Attestation: the manifest digest must carry a green eval-gate run.
    digest = _prompt_manifest_digest(pinned)
    try:
        attestation = json.loads(attestation_path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        violations.append(Violation(
            attestation_path, 0,
            f"eval-gate attestation missing/unreadable ({exc}) — a prompt-"
            f"manifest change requires an eval run: {_PROMPT_ATTEST_HINT}",
        ))
        return violations
    if attestation.get("manifest_digest") != digest:
        violations.append(Violation(
            attestation_path, 0,
            "prompt manifest changed WITHOUT a fresh eval-gate attestation "
            f"(attested digest {str(attestation.get('manifest_digest'))[:12]}… != "
            f"current {digest[:12]}…) — {_PROMPT_ATTEST_HINT}",
        ))
    if attestation.get("verdict") != "PASS":
        violations.append(Violation(
            attestation_path, 0,
            f"attested eval-gate verdict is {attestation.get('verdict')!r}, not "
            "PASS — the prompt change did not clear the eval gate; fix the "
            "regression (or re-baseline deliberately) and re-attest",
        ))
    return violations


# ── Registry ─────────────────────────────────────────────────────────────────

GUARDS: list[Guard] = [
    Guard(
        name="backend.no-print",
        description="No print() in backend/app/ — use structlog.",
        check=_backend_no_print,
        fix_hint="Replace print(...) with logger.info(...) / .warning(...) / .error(...).",
    ),
    Guard(
        name="backend.analysis-router",
        description="Direct calls to run_triage_agent / RulesEngine / MLClassifier — must go through services.analysis_router.",
        check=_backend_analysis_router_bypass,
        fix_hint="Replace with `await analysis_router.classify_test(...)` so mode + fallback + routing metadata are recorded.",
    ),
    Guard(
        name="backend.finalize-run",
        description="Ingestion owners (ingestion_pipeline, worker.tasks) must call finalize_run().",
        check=_backend_finalize_run_wired,
        fix_hint="After persisting TestCase rows, call services.ingestion_pipeline.finalize_run(...) inside a try/except.",
    ),
    Guard(
        name="backend.pii-log-redaction",
        description="logger.* calls passing PII (email / password / api_key) verbatim.",
        check=_backend_pii_log_redaction,
        fix_hint="Wrap the value with privacy_service.sanitize_for_logging(...) before logging.",
    ),
    Guard(
        name="backend.structlog-positional-args",
        description=(
            "structlog logger called with positional %s args — explodes "
            "with TypeError mid-call (BoundLogger.warning is (event, **kw))."
        ),
        check=_backend_structlog_positional_args,
        fix_hint=(
            "Use kwargs: ``logger.warning(\"event_name\", error=str(exc))``. "
            "See memory/feedback_structlog_positional_args.md."
        ),
    ),
    Guard(
        name="backend.audit-write-discipline",
        description=(
            "Audit tables (settings_audit_log / access_audit_logs / "
            "test_case_audit_logs / identity_events) are append-only: no "
            "UPDATE anywhere, no DELETE outside the retention purge."
        ),
        check=_backend_audit_write_discipline,
        fix_hint=(
            "Append a NEW audit row instead of mutating one. If a purge is "
            "genuinely needed, extend services/retention_service.py (the "
            "audit-clock deleter) rather than deleting inline — the model "
            "docstrings promise exactly that boundary."
        ),
    ),
    Guard(
        name="frontend.clipboard-util",
        description="navigator.clipboard.writeText outside utils/clipboard.ts — breaks on HTTP origins.",
        check=_frontend_clipboard_util,
        fix_hint="`import { copyTextToClipboard } from '@/utils/clipboard'` and call that instead.",
    ),
    Guard(
        name="frontend.ai-output-hedging",
        description=(
            "AI output rendered as a verdict — a bare \"Root cause:\", "
            "\"Root Cause Summary\", \"the cause is …\" or \"is caused by\" "
            "in UI copy. AI conclusions are suggestions to confirm."
        ),
        check=_frontend_ai_output_hedging,
        fix_hint=(
            "Hedge the copy (\"Suggested root cause\", \"likely caused by\") "
            "and render the conclusion inside components/ai/AISuggestion so "
            "it carries the badge, basis and provenance (US-15.1). Pipeline "
            "STAGE names like \"Root Cause Analysis\" are already allowed."
        ),
    ),
    Guard(
        name="frontend.all-projects-literal",
        description="Literal 'all' assigned to project_id — never send to backend.",
        check=_frontend_all_projects_literal,
        fix_hint="Use `activeProjectId === ALL_PROJECTS_ID` guard and pass `null` to the API.",
    ),
    Guard(
        name="frontend.refresh-intervals-from-config",
        description="SWR poll cadences come from config/refreshIntervals.ts tiers.",
        check=_frontend_refresh_intervals_from_config,
        fix_hint="`import { REFRESH_INTERVALS } from '@/config/refreshIntervals'` and use REALTIME / ACTIVE / POLLING / BACKGROUND (0 = disabled is fine).",
    ),
    Guard(
        name="frontend.single-axios",
        description="Only one axios.create() allowed (services/api.ts).",
        check=_frontend_single_axios,
        fix_hint="`import { api } from '@/services/api'` and reuse it (or use getData/postData from services/http.ts).",
    ),
    Guard(
        name="frontend.swr-only-fetching",
        description="Pages must fetch via SWR hooks, not raw fetch/axios.",
        check=_frontend_swr_only_fetching,
        fix_hint="Move the call into a hook under src/hooks/ that wraps useSWR / useProjectScopedSWR.",
    ),
    Guard(
        name="database.single-alembic-head",
        description="Single Alembic head — no merge conflicts in down_revision chain.",
        check=_database_single_alembic_head,
        fix_hint="Re-base your migration's down_revision onto the current head (see feedback_alembic_head_conflicts memory).",
    ),
    Guard(
        name="database.downgrade-implemented",
        description="Every migration has a real downgrade() body.",
        check=_database_downgrade_implemented,
        fix_hint="Implement the inverse operations, or add a one-line docstring explaining why rollback is unsupported.",
    ),
    Guard(
        name="agents.base-agent-subclass",
        description="Every agent in app/agents/ subclasses BaseAgent.",
        check=_agents_base_agent_subclass,
        fix_hint="`class FooAgent(BaseAgent):` so stage tracking + decision log + OTEL spans work.",
    ),
    Guard(
        name="agents.log-decision-present",
        description="Every BaseAgent subclass calls self.log_decision(...) at least once.",
        check=_agents_log_decision_present,
        fix_hint="Log every non-trivial routing/fallback/skip branch via `await self.log_decision(...)`.",
    ),
    Guard(
        name="agents.routing-metadata",
        description="analysis_router.classify_test populates the _routing dict on every return.",
        check=_agents_routing_metadata_populated,
        fix_hint="Set `result['_routing'] = {...}` before returning from classify_test (mode_requested / mode_resolved / mode_used / fallback_*).",
    ),
    Guard(
        name="ai.prompt-manifest-sync",
        description=(
            "Every LLM prompt (registry + MCP templates) matches its pinned "
            "hash in prompt_manifest.json, and the manifest digest carries a "
            "green eval-gate attestation (prompt_manifest_eval.json)."
        ),
        check=_ai_prompt_manifest_sync,
        fix_hint=(
            "Bump the prompt's version in app/services/prompt_registry.py "
            "(or PROMPT_TEMPLATE_VERSIONS for mcp.* prompts), then: "
            + _PROMPT_ATTEST_HINT
            + ". See architecture/AI_EVALUATION.md."
        ),
    ),
    Guard(
        name="homelab.build-tag-placeholder",
        description=(
            "k8s/overlays/homelab/kustomization.yaml must keep newTag: "
            "BUILD_TAG_PLACEHOLDER for every locally-built image at rest."
        ),
        check=_homelab_build_tag_placeholder,
        fix_hint=(
            "Run `git checkout -- k8s/overlays/homelab/kustomization.yaml` "
            "to restore the placeholder. A previous deploy-homelab.sh run "
            "was likely killed before its EXIT trap could fire."
        ),
    ),
]

GUARD_BY_NAME = {g.name: g for g in GUARDS}


# ── CLI ──────────────────────────────────────────────────────────────────────


def run_guard(guard: Guard, update_baseline: bool) -> bool:
    baseline = guard.load_baseline()
    raw = guard.check()
    keys = {v.key for v in raw}
    new = [v for v in raw if v.key not in baseline]
    stale = baseline - keys

    if update_baseline:
        guard.save_baseline(keys)
        print(f"{BLUE}== {guard.name}{RESET}: wrote {len(keys)} entries to "
              f"{guard.baseline_path.relative_to(REPO_ROOT)}")
        return True

    if not new and not stale:
        print(f"{GREEN}OK{RESET}  {guard.name} {DIM}({guard.description}){RESET}")
        return True

    if stale:
        # Baseline drift means the code is cleaner than the baseline
        # claims. Not a failure — just nudge the developer to rerun
        # ``--update-baseline``.
        print(f"{YELLOW}!!{RESET}  {guard.name}: {len(stale)} baseline "
              f"entries are stale (the code is fixed). Run "
              f"`python scripts/quality_gate.py --only {guard.name} "
              f"--update-baseline` to prune.")
        for k in sorted(stale):
            print(f"    {DIM}stale: {k}{RESET}")

    if new:
        print(f"{RED}FAIL{RESET} {guard.name} -- {len(new)} new violation"
              f"{'s' if len(new) != 1 else ''}:")
        for v in new:
            print(f"    {v.format()}")
        if guard.fix_hint:
            print(f"  {DIM}fix: {guard.fix_hint}{RESET}")
        return False
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--list", action="store_true",
                        help="Print every guard name and exit.")
    parser.add_argument("--only", nargs="+", metavar="GUARD",
                        help="Run a subset of guards (by name).")
    parser.add_argument("--update-baseline", action="store_true",
                        help="Rewrite the baseline file(s) for the selected guard(s). "
                             "Disabled in CI by convention — review baseline changes in PRs.")
    args = parser.parse_args()

    if args.list:
        for g in GUARDS:
            print(f"  {g.name:<40}  {g.description}")
        return 0

    selected: list[Guard]
    if args.only:
        unknown = [n for n in args.only if n not in GUARD_BY_NAME]
        if unknown:
            print(f"{RED}unknown guard(s){RESET}: {unknown}", file=sys.stderr)
            print(f"  valid names: {', '.join(GUARD_BY_NAME)}", file=sys.stderr)
            return 2
        selected = [GUARD_BY_NAME[n] for n in args.only]
    else:
        selected = GUARDS

    print(f"{BLUE}TestLookup quality gate — {len(selected)} guard"
          f"{'s' if len(selected) != 1 else ''}{RESET}")
    failures = 0
    for g in selected:
        ok = run_guard(g, update_baseline=args.update_baseline)
        if not ok:
            failures += 1

    if failures:
        print(f"\n{RED}quality gate FAILED -- {failures} guard"
              f"{'s' if failures != 1 else ''} blocked{RESET}", file=sys.stderr)
        return 1
    print(f"\n{GREEN}quality gate passed{RESET}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
