#!/usr/bin/env python3
"""Render k8s/monitoring/prometheusrule.yaml from the one alert-rules file.

``infra/monitoring/prometheus-rules/testlookup-alerts.yml`` is what the
Compose monitoring stack loads. Kubernetes clusters running the Prometheus
Operator need the same rules wrapped in a ``PrometheusRule`` custom resource;
there was none under ``k8s/`` (re-audit H5 follow-up), so no alert, including
TestLookupFinalizeStepFailing, could fire on a cluster deployment.

The CR is GENERATED so the two cannot drift;
``backend/tests/regression/test_alert_rules_are_deployable.py`` fails when the
committed file is stale. Run from the repo root::

    python scripts/render_prometheusrule.py
"""
from __future__ import annotations

from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "infra" / "monitoring" / "prometheus-rules" / "testlookup-alerts.yml"
TARGET = ROOT / "k8s" / "monitoring" / "prometheusrule.yaml"

HEADER = (
    "# GENERATED by scripts/render_prometheusrule.py from\n"
    "# infra/monitoring/prometheus-rules/testlookup-alerts.yml. Do not edit by\n"
    "# hand: edit the source and re-run the script.\n"
    "#\n"
    "# Needs the Prometheus Operator CRDs (monitoring.coreos.com/v1). Your\n"
    "# Prometheus must select this rule: kube-prometheus-stack's default\n"
    "# ruleSelector matches the label `release: <helm release name>`; add it\n"
    "# with a kustomize patch, or set ruleSelectorNilUsesHelmValues=false.\n"
)


def render() -> str:
    rules = yaml.safe_load(SOURCE.read_text(encoding="utf-8"))
    resource = {
        "apiVersion": "monitoring.coreos.com/v1",
        "kind": "PrometheusRule",
        "metadata": {
            "name": "testlookup-alerts",
            "namespace": "testlookup",
            "labels": {
                "app.kubernetes.io/name": "testlookup",
                "app.kubernetes.io/part-of": "testlookup",
                "role": "alert-rules",
            },
        },
        "spec": {"groups": rules["groups"]},
    }
    return HEADER + yaml.safe_dump(resource, sort_keys=False, width=1000, allow_unicode=True)


def main() -> int:
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_bytes(render().encode("utf-8"))
    print(f"wrote {TARGET.relative_to(ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
