"""Add role_actions JSONB column to ai_analysis for role-aware recommended actions

Revision ID: 0016
Revises: 0015
Create Date: 2026-03-31

Changes:
  - ai_analysis: add role_actions JSONB
    Stores role-aware recommended actions keyed by qa/developer/sre/release_manager,
    generated by the ReAct agent as part of structured root-cause analysis.
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0016"
down_revision = "0015"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "ai_analysis",
        sa.Column(
            "role_actions",
            sa.JSON(),
            nullable=True,
            comment="Role-aware recommended actions: {qa, developer, sre, release_manager}",
        ),
    )


def downgrade() -> None:
    op.drop_column("ai_analysis", "role_actions")
